In [35]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


import mxnet as mx
from gluonts.dataset.pandas import PandasDataset
from gluonts.mx import DeepAREstimator, Trainer, MQRNNEstimator, TemporalFusionTransformerEstimator
# from gluonts.distribution.neg_binomial import NegativeBinomialOutput
from gluonts.mx.distribution.neg_binomial import NegativeBinomialOutput
from gluonts.mx.trainer.callback import TrainingHistory


from gluonts.dataset.util import to_pandas
from gluonts.dataset.pandas import PandasDataset
from gluonts.evaluation.backtest import make_evaluation_predictions

In [36]:
mx.context.num_gpus()

0

In [37]:
df = pd.read_csv('../../../data/Merged-update_hourly.csv')
# df = pd.read_csv('pollution.csv')

In [38]:
df

Time  WS_S1  WS_S4  FLOW_S25A  GATE_S25A  HWS_S25A  TWS_S25A  \
0        1/1/10 00:00   0.33   0.34        0.0        0.0      2.17      0.49   
1        1/1/10 01:00  -0.29  -0.28        0.0        0.0      2.17      0.02   
2        1/1/10 02:00  -0.81  -0.73        0.0        0.0      2.17     -0.49   
3        1/1/10 03:00  -0.98  -0.85        0.0        0.0      2.15     -0.75   
4        1/1/10 04:00  -0.69  -0.49        0.0        0.0      2.13     -0.55   
...               ...    ...    ...        ...        ...       ...       ...   
96427  12/31/20 19:00   1.24   1.19        0.0        0.0      1.92      1.25   
96428  12/31/20 20:00   1.62   1.61        0.0        0.0      1.92      1.64   
96429  12/31/20 21:00   1.98   1.90        0.0        0.0      1.93      2.00   
96430  12/31/20 22:00   2.13   2.03        0.0        0.0      1.94      2.13   
96431  12/31/20 23:00   1.96   1.81        0.0        0.0      1.96      1.98   

       FLOW_S25B  GATE_S25B  GATE_S25B2  HWS_S25B  TWS_S25B  PUMP_S25B  \
0            0.0        0.0         0.0      2.84      0.58        0.0   
1            0.0        0.0         0.0      2.84     -0.07        0.0   
2            0.0        0.0         0.0      2.84     -0.62        0.0   
3            0.0        0.0         0.0      2.83     -0.82        0.0   
4            0.0        0.0         0.0      2.84     -0.53        0.0   
...          ...        ...         ...       ...       ...        ...   
96427        0.0        0.0         0.0      2.86      1.31        0.0   
96428        0.0        0.0         0.0      2.88      1.68        0.0   
96429        0.0        0.0         0.0      2.89      2.04        0.0   
96430        0.0        0.0         0.0      2.90      2.21        0.0   
96431        0.0        0.0         0.0      2.91      2.06        0.0   

       FLOW_S26  GATE_S26_1  GATE_S26_2  HWS_S26  TWS_S26  PUMP_S26  MEAN_RAIN  
0          0.00         0.0        0.00     2.78    0.505       0.0        0.0  
1          0.00         0.0        0.00     2.78   -0.110       0.0        0.0  
2          0.00         0.0        0.00     2.79   -0.650       0.0        0.0  
3          0.00         0.0        0.00     2.79   -0.850       0.0        0.0  
4          0.00         0.0        0.00     2.79   -0.550       0.0        0.0  
...         ...         ...         ...      ...      ...       ...        ...  
96427    456.34         0.0        2.61     2.49    1.290       0.0        0.0  
96428    380.19         0.0        2.62     2.48    1.660       0.0        0.0  
96429    287.12         0.0        2.62     2.54    2.040       0.0        0.0  
96430    253.27         0.0        2.62     2.58    2.180       0.0        0.0  
96431    294.00         0.0        2.62     2.59    2.050       0.0        0.0  

[96432 rows x 20 columns]

In [39]:
df.loc[:, 'timestamp'] = pd.to_datetime(df.loc[:, 'Time'], infer_datetime_format=True)

In [40]:
df

Time  WS_S1  WS_S4  FLOW_S25A  GATE_S25A  HWS_S25A  TWS_S25A  \
0        1/1/10 00:00   0.33   0.34        0.0        0.0      2.17      0.49   
1        1/1/10 01:00  -0.29  -0.28        0.0        0.0      2.17      0.02   
2        1/1/10 02:00  -0.81  -0.73        0.0        0.0      2.17     -0.49   
3        1/1/10 03:00  -0.98  -0.85        0.0        0.0      2.15     -0.75   
4        1/1/10 04:00  -0.69  -0.49        0.0        0.0      2.13     -0.55   
...               ...    ...    ...        ...        ...       ...       ...   
96427  12/31/20 19:00   1.24   1.19        0.0        0.0      1.92      1.25   
96428  12/31/20 20:00   1.62   1.61        0.0        0.0      1.92      1.64   
96429  12/31/20 21:00   1.98   1.90        0.0        0.0      1.93      2.00   
96430  12/31/20 22:00   2.13   2.03        0.0        0.0      1.94      2.13   
96431  12/31/20 23:00   1.96   1.81        0.0        0.0      1.96      1.98   

       FLOW_S25B  GATE_S25B  GATE_S25B2  ...  TWS_S25B  PUMP_S25B  FLOW_S26  \
0            0.0        0.0         0.0  ...      0.58        0.0      0.00   
1            0.0        0.0         0.0  ...     -0.07        0.0      0.00   
2            0.0        0.0         0.0  ...     -0.62        0.0      0.00   
3            0.0        0.0         0.0  ...     -0.82        0.0      0.00   
4            0.0        0.0         0.0  ...     -0.53        0.0      0.00   
...          ...        ...         ...  ...       ...        ...       ...   
96427        0.0        0.0         0.0  ...      1.31        0.0    456.34   
96428        0.0        0.0         0.0  ...      1.68        0.0    380.19   
96429        0.0        0.0         0.0  ...      2.04        0.0    287.12   
96430        0.0        0.0         0.0  ...      2.21        0.0    253.27   
96431        0.0        0.0         0.0  ...      2.06        0.0    294.00   

       GATE_S26_1  GATE_S26_2  HWS_S26  TWS_S26  PUMP_S26  MEAN_RAIN  \
0             0.0        0.00     2.78    0.505       0.0        0.0   
1             0.0        0.00     2.78   -0.110       0.0        0.0   
2             0.0        0.00     2.79   -0.650       0.0        0.0   
3             0.0        0.00     2.79   -0.850       0.0        0.0   
4             0.0        0.00     2.79   -0.550       0.0        0.0   
...           ...         ...      ...      ...       ...        ...   
96427         0.0        2.61     2.49    1.290       0.0        0.0   
96428         0.0        2.62     2.48    1.660       0.0        0.0   
96429         0.0        2.62     2.54    2.040       0.0        0.0   
96430         0.0        2.62     2.58    2.180       0.0        0.0   
96431         0.0        2.62     2.59    2.050       0.0        0.0   

                timestamp  
0     2010-01-01 00:00:00  
1     2010-01-01 01:00:00  
2     2010-01-01 02:00:00  
3     2010-01-01 03:00:00  
4     2010-01-01 04:00:00  
...                   ...  
96427 2020-12-31 19:00:00  
96428 2020-12-31 20:00:00  
96429 2020-12-31 21:00:00  
96430 2020-12-31 22:00:00  
96431 2020-12-31 23:00:00  

[96432 rows x 21 columns]

In [41]:
df.columns

Index(['Time', 'WS_S1', 'WS_S4', 'FLOW_S25A', 'GATE_S25A', 'HWS_S25A',
       'TWS_S25A', 'FLOW_S25B', 'GATE_S25B', 'GATE_S25B2', 'HWS_S25B',
       'TWS_S25B', 'PUMP_S25B', 'FLOW_S26', 'GATE_S26_1', 'GATE_S26_2',
       'HWS_S26', 'TWS_S26', 'PUMP_S26', 'MEAN_RAIN', 'timestamp'],
      dtype='object')

In [42]:
train_df = df.iloc[:int(len(df)*0.8), :]
test_df = df.iloc[int(len(df)*0.8):, :]

In [43]:
train_df.shape

(77145, 21)

In [44]:
test_df

Time  WS_S1  WS_S4  FLOW_S25A  GATE_S25A  HWS_S25A  TWS_S25A  \
77145  10/20/18 09:00   1.06   1.01        0.0        0.0      2.41      1.07   
77146  10/20/18 10:00   0.68   0.63        0.0        0.0      2.41      0.71   
77147  10/20/18 11:00   0.31   0.32        0.0        0.0      2.41      0.33   
77148  10/20/18 12:00   0.20   0.23        0.0        0.0      2.40      0.24   
77149  10/20/18 13:00   0.41   0.42        0.0        0.0      2.39      0.42   
...               ...    ...    ...        ...        ...       ...       ...   
96427  12/31/20 19:00   1.24   1.19        0.0        0.0      1.92      1.25   
96428  12/31/20 20:00   1.62   1.61        0.0        0.0      1.92      1.64   
96429  12/31/20 21:00   1.98   1.90        0.0        0.0      1.93      2.00   
96430  12/31/20 22:00   2.13   2.03        0.0        0.0      1.94      2.13   
96431  12/31/20 23:00   1.96   1.81        0.0        0.0      1.96      1.98   

       FLOW_S25B  GATE_S25B  GATE_S25B2  ...  TWS_S25B  PUMP_S25B  FLOW_S26  \
77145        0.0        0.0         0.0  ...      1.15        0.0    469.19   
77146        0.0        0.0         0.0  ...      0.82        0.0      0.00   
77147        0.0        0.0         0.0  ...      0.42        0.0      0.00   
77148        0.0        0.0         0.0  ...      0.35        0.0      0.00   
77149        0.0        0.0         0.0  ...      0.48        0.0      0.00   
...          ...        ...         ...  ...       ...        ...       ...   
96427        0.0        0.0         0.0  ...      1.31        0.0    456.34   
96428        0.0        0.0         0.0  ...      1.68        0.0    380.19   
96429        0.0        0.0         0.0  ...      2.04        0.0    287.12   
96430        0.0        0.0         0.0  ...      2.21        0.0    253.27   
96431        0.0        0.0         0.0  ...      2.06        0.0    294.00   

       GATE_S26_1  GATE_S26_2  HWS_S26  TWS_S26  PUMP_S26  MEAN_RAIN  \
77145         0.0        2.61     2.35     1.11       0.0        0.0   
77146         0.0        0.00     2.62     0.72       0.0        0.0   
77147         0.0        0.00     2.62     0.37       0.0        0.0   
77148         0.0        0.00     2.67     0.28       0.0        0.0   
77149         0.0        0.00     2.72     0.45       0.0        0.0   
...           ...         ...      ...      ...       ...        ...   
96427         0.0        2.61     2.49     1.29       0.0        0.0   
96428         0.0        2.62     2.48     1.66       0.0        0.0   
96429         0.0        2.62     2.54     2.04       0.0        0.0   
96430         0.0        2.62     2.58     2.18       0.0        0.0   
96431         0.0        2.62     2.59     2.05       0.0        0.0   

                timestamp  
77145 2018-10-20 09:00:00  
77146 2018-10-20 10:00:00  
77147 2018-10-20 11:00:00  
77148 2018-10-20 12:00:00  
77149 2018-10-20 13:00:00  
...                   ...  
96427 2020-12-31 19:00:00  
96428 2020-12-31 20:00:00  
96429 2020-12-31 21:00:00  
96430 2020-12-31 22:00:00  
96431 2020-12-31 23:00:00  

[19287 rows x 21 columns]

In [45]:
train_ds = PandasDataset(
    train_df,
    target = ['TWS_S26'],
    timestamp = 'timestamp',
    feat_dynamic_real = ['WS_S1', 'TWS_S25A', 'TWS_S25B', 'WS_S4', 'FLOW_S25A', 'GATE_S25A', 'HWS_S25A',
       'FLOW_S25B', 'GATE_S25B', 'GATE_S25B2', 'HWS_S25B',
       'PUMP_S25B', 'FLOW_S26', 'GATE_S26_1', 'GATE_S26_2',
       'HWS_S26', 'PUMP_S26', 'MEAN_RAIN'],
    freq = 'H'
)

In [46]:
test_ds = PandasDataset(
    test_df,
    target = ['TWS_S26'],
    timestamp = 'timestamp',
    feat_dynamic_real = ['WS_S1', 'TWS_S25A', 'TWS_S25B', 'WS_S4', 'FLOW_S25A', 'GATE_S25A', 'HWS_S25A',
       'FLOW_S25B', 'GATE_S25B', 'GATE_S25B2', 'HWS_S25B',
       'PUMP_S25B', 'FLOW_S26', 'GATE_S26_1', 'GATE_S26_2',
       'HWS_S26', 'PUMP_S26', 'MEAN_RAIN'],
    freq = 'H'
)

#### training

In [47]:
K = 48
n_hours = 24*3

In [48]:
trainer=Trainer(
    learning_rate=1e-3,
    epochs=150,
    num_batches_per_epoch=100,
    add_default_callbacks=True,
    weight_decay=1e-06)

estimator = TemporalFusionTransformerEstimator(
    prediction_length=K,
    freq="H",
#     use_feat_dynamic_real=True,
    batch_size=32,
    trainer=trainer,
    dropout_rate=0.3,
    hidden_dim=64,
    num_heads=2,
)

model_26 = estimator.train(train_ds)

100%|███████████████████████████████████████████████| 100/100 [05:28<00:00,  3.29s/it, epoch=132/150, avg_epoch_loss=0.0316]


100%|███████████████████████████████████████████████| 100/100 [07:41<00:00,  4.61s/it, epoch=150/150, avg_epoch_loss=0.0321]


#### predicted y

In [49]:
quantiles = ['0.5', '0.1', '0.9']
q50 = 0

In [50]:
test_ds_predict_q50_all = np.array([])

for i in range(len(test_df)-n_hours-K+1):
    print(i)
    
    cut = df.iloc[len(train_df)+i:len(train_df)+i+n_hours+K, :]

    test_ds = PandasDataset(
    cut,
    target = 'TWS_S26',
    timestamp = 'timestamp',
    feat_dynamic_real = ['WS_S1', 'TWS_S25A', 'TWS_S25B', 'WS_S4', 'FLOW_S25A', 'GATE_S25A', 'HWS_S25A',
       'FLOW_S25B', 'GATE_S25B', 'GATE_S25B2', 'HWS_S25B',
       'PUMP_S25B', 'FLOW_S26', 'GATE_S26_1', 'GATE_S26_2',
       'HWS_S26', 'PUMP_S26', 'MEAN_RAIN'],
        freq = 'H'
    )
    
    forecast_it, ts_it = make_evaluation_predictions(dataset=test_ds, predictor=model_26, num_samples=200)
    test_ds_predict = list(forecast_it)
    test_ds_predict_quantiles = test_ds_predict[0].forecast_array
    test_ds_predict_q50 = test_ds_predict_quantiles.mean(axis=0)
    test_ds_predict_q50_all = np.concatenate((test_ds_predict_q50_all, test_ds_predict_q50), axis=None)
    print(test_ds_predict_q50_all)
    print(test_ds_predict_q50_all.shape)
    print('------')

0
[2.51323962 1.98924065 1.47266853 0.98042303 0.51623917 0.31311059
 0.4915283  1.02235365 1.60488594 2.09089375 2.51266265 2.67695332
 2.51126575 1.99715519 1.43865931 0.93535393 0.43923306 0.13391285
 0.17786956 0.6562708  1.31081212 1.86701143 2.39162993 2.7447567
 2.78552365 2.42154932 1.80927503 1.30479717 0.81478333 0.39877805
 0.26570162 0.55420023 1.15904009 1.71582699 2.21274495 2.56378078
 2.63389587 2.33708477 1.76076174 1.26424015 0.74313277 0.25665909
 0.05603945 0.22033411 0.79564714 1.44398463 1.98395431 2.48369431]
(48,)
------
1
[2.51323962 1.98924065 1.47266853 0.98042303 0.51623917 0.31311059
 0.4915283  1.02235365 1.60488594 2.09089375 2.51266265 2.67695332
 2.51126575 1.99715519 1.43865931 0.93535393 0.43923306 0.13391285
 0.17786956 0.6562708  1.31081212 1.86701143 2.39162993 2.7447567
 2.78552365 2.42154932 1.80927503 1.30479717 0.81478333 0.39877805
 0.26570162 0.55420023 1.15904009 1.71582699 2.21274495 2.56378078
 2.63389587 2.33708477 1.76076174 1.26424015 0

[2.51323962 1.98924065 1.47266853 0.98042303 0.51623917 0.31311059
 0.4915283  1.02235365 1.60488594 2.09089375 2.51266265 2.67695332
 2.51126575 1.99715519 1.43865931 0.93535393 0.43923306 0.13391285
 0.17786956 0.6562708  1.31081212 1.86701143 2.39162993 2.7447567
 2.78552365 2.42154932 1.80927503 1.30479717 0.81478333 0.39877805
 0.26570162 0.55420023 1.15904009 1.71582699 2.21274495 2.56378078
 2.63389587 2.33708477 1.76076174 1.26424015 0.74313277 0.25665909
 0.05603945 0.22033411 0.79564714 1.44398463 1.98395431 2.48369431
 2.0324924  1.50960457 1.02110279 0.53950405 0.32399324 0.4993751
 1.03678083 1.63141668 2.12082982 2.54747581 2.71403599 2.55012417
 2.040766   1.47410297 0.96508646 0.46053386 0.14106727 0.17570503
 0.6460464  1.30219412 1.86458623 2.39635301 2.76107407 2.8113625
 2.45195532 1.83597672 1.32626975 0.83210534 0.41267362 0.27407745
 0.55704463 1.164976   1.72903872 2.23030949 2.59118581 2.6693294
 2.37822032 1.79680669 1.29262698 0.76683664 0.27276459 0.06426819

[2.51323962 1.98924065 1.47266853 0.98042303 0.51623917 0.31311059
 0.4915283  1.02235365 1.60488594 2.09089375 2.51266265 2.67695332
 2.51126575 1.99715519 1.43865931 0.93535393 0.43923306 0.13391285
 0.17786956 0.6562708  1.31081212 1.86701143 2.39162993 2.7447567
 2.78552365 2.42154932 1.80927503 1.30479717 0.81478333 0.39877805
 0.26570162 0.55420023 1.15904009 1.71582699 2.21274495 2.56378078
 2.63389587 2.33708477 1.76076174 1.26424015 0.74313277 0.25665909
 0.05603945 0.22033411 0.79564714 1.44398463 1.98395431 2.48369431
 2.0324924  1.50960457 1.02110279 0.53950405 0.32399324 0.4993751
 1.03678083 1.63141668 2.12082982 2.54747581 2.71403599 2.55012417
 2.040766   1.47410297 0.96508646 0.46053386 0.14106727 0.17570503
 0.6460464  1.30219412 1.86458623 2.39635301 2.76107407 2.8113625
 2.45195532 1.83597672 1.32626975 0.83210534 0.41267362 0.27407745
 0.55704463 1.164976   1.72903872 2.23030949 2.59118581 2.6693294
 2.37822032 1.79680669 1.29262698 0.76683664 0.27276459 0.06426819

[2.51323962 1.98924065 1.47266853 0.98042303 0.51623917 0.31311059
 0.4915283  1.02235365 1.60488594 2.09089375 2.51266265 2.67695332
 2.51126575 1.99715519 1.43865931 0.93535393 0.43923306 0.13391285
 0.17786956 0.6562708  1.31081212 1.86701143 2.39162993 2.7447567
 2.78552365 2.42154932 1.80927503 1.30479717 0.81478333 0.39877805
 0.26570162 0.55420023 1.15904009 1.71582699 2.21274495 2.56378078
 2.63389587 2.33708477 1.76076174 1.26424015 0.74313277 0.25665909
 0.05603945 0.22033411 0.79564714 1.44398463 1.98395431 2.48369431
 2.0324924  1.50960457 1.02110279 0.53950405 0.32399324 0.4993751
 1.03678083 1.63141668 2.12082982 2.54747581 2.71403599 2.55012417
 2.040766   1.47410297 0.96508646 0.46053386 0.14106727 0.17570503
 0.6460464  1.30219412 1.86458623 2.39635301 2.76107407 2.8113625
 2.45195532 1.83597672 1.32626975 0.83210534 0.41267362 0.27407745
 0.55704463 1.164976   1.72903872 2.23030949 2.59118581 2.6693294
 2.37822032 1.79680669 1.29262698 0.76683664 0.27276459 0.06426819

[2.51323962 1.98924065 1.47266853 0.98042303 0.51623917 0.31311059
 0.4915283  1.02235365 1.60488594 2.09089375 2.51266265 2.67695332
 2.51126575 1.99715519 1.43865931 0.93535393 0.43923306 0.13391285
 0.17786956 0.6562708  1.31081212 1.86701143 2.39162993 2.7447567
 2.78552365 2.42154932 1.80927503 1.30479717 0.81478333 0.39877805
 0.26570162 0.55420023 1.15904009 1.71582699 2.21274495 2.56378078
 2.63389587 2.33708477 1.76076174 1.26424015 0.74313277 0.25665909
 0.05603945 0.22033411 0.79564714 1.44398463 1.98395431 2.48369431
 2.0324924  1.50960457 1.02110279 0.53950405 0.32399324 0.4993751
 1.03678083 1.63141668 2.12082982 2.54747581 2.71403599 2.55012417
 2.040766   1.47410297 0.96508646 0.46053386 0.14106727 0.17570503
 0.6460464  1.30219412 1.86458623 2.39635301 2.76107407 2.8113625
 2.45195532 1.83597672 1.32626975 0.83210534 0.41267362 0.27407745
 0.55704463 1.164976   1.72903872 2.23030949 2.59118581 2.6693294
 2.37822032 1.79680669 1.29262698 0.76683664 0.27276459 0.06426819

[2.51323962 1.98924065 1.47266853 0.98042303 0.51623917 0.31311059
 0.4915283  1.02235365 1.60488594 2.09089375 2.51266265 2.67695332
 2.51126575 1.99715519 1.43865931 0.93535393 0.43923306 0.13391285
 0.17786956 0.6562708  1.31081212 1.86701143 2.39162993 2.7447567
 2.78552365 2.42154932 1.80927503 1.30479717 0.81478333 0.39877805
 0.26570162 0.55420023 1.15904009 1.71582699 2.21274495 2.56378078
 2.63389587 2.33708477 1.76076174 1.26424015 0.74313277 0.25665909
 0.05603945 0.22033411 0.79564714 1.44398463 1.98395431 2.48369431
 2.0324924  1.50960457 1.02110279 0.53950405 0.32399324 0.4993751
 1.03678083 1.63141668 2.12082982 2.54747581 2.71403599 2.55012417
 2.040766   1.47410297 0.96508646 0.46053386 0.14106727 0.17570503
 0.6460464  1.30219412 1.86458623 2.39635301 2.76107407 2.8113625
 2.45195532 1.83597672 1.32626975 0.83210534 0.41267362 0.27407745
 0.55704463 1.164976   1.72903872 2.23030949 2.59118581 2.6693294
 2.37822032 1.79680669 1.29262698 0.76683664 0.27276459 0.06426819

[2.51323962 1.98924065 1.47266853 0.98042303 0.51623917 0.31311059
 0.4915283  1.02235365 1.60488594 2.09089375 2.51266265 2.67695332
 2.51126575 1.99715519 1.43865931 0.93535393 0.43923306 0.13391285
 0.17786956 0.6562708  1.31081212 1.86701143 2.39162993 2.7447567
 2.78552365 2.42154932 1.80927503 1.30479717 0.81478333 0.39877805
 0.26570162 0.55420023 1.15904009 1.71582699 2.21274495 2.56378078
 2.63389587 2.33708477 1.76076174 1.26424015 0.74313277 0.25665909
 0.05603945 0.22033411 0.79564714 1.44398463 1.98395431 2.48369431
 2.0324924  1.50960457 1.02110279 0.53950405 0.32399324 0.4993751
 1.03678083 1.63141668 2.12082982 2.54747581 2.71403599 2.55012417
 2.040766   1.47410297 0.96508646 0.46053386 0.14106727 0.17570503
 0.6460464  1.30219412 1.86458623 2.39635301 2.76107407 2.8113625
 2.45195532 1.83597672 1.32626975 0.83210534 0.41267362 0.27407745
 0.55704463 1.164976   1.72903872 2.23030949 2.59118581 2.6693294
 2.37822032 1.79680669 1.29262698 0.76683664 0.27276459 0.06426819

[2.51323962 1.98924065 1.47266853 0.98042303 0.51623917 0.31311059
 0.4915283  1.02235365 1.60488594 2.09089375 2.51266265 2.67695332
 2.51126575 1.99715519 1.43865931 0.93535393 0.43923306 0.13391285
 0.17786956 0.6562708  1.31081212 1.86701143 2.39162993 2.7447567
 2.78552365 2.42154932 1.80927503 1.30479717 0.81478333 0.39877805
 0.26570162 0.55420023 1.15904009 1.71582699 2.21274495 2.56378078
 2.63389587 2.33708477 1.76076174 1.26424015 0.74313277 0.25665909
 0.05603945 0.22033411 0.79564714 1.44398463 1.98395431 2.48369431
 2.0324924  1.50960457 1.02110279 0.53950405 0.32399324 0.4993751
 1.03678083 1.63141668 2.12082982 2.54747581 2.71403599 2.55012417
 2.040766   1.47410297 0.96508646 0.46053386 0.14106727 0.17570503
 0.6460464  1.30219412 1.86458623 2.39635301 2.76107407 2.8113625
 2.45195532 1.83597672 1.32626975 0.83210534 0.41267362 0.27407745
 0.55704463 1.164976   1.72903872 2.23030949 2.59118581 2.6693294
 2.37822032 1.79680669 1.29262698 0.76683664 0.27276459 0.06426819

[2.51323962 1.98924065 1.47266853 ... 0.64120817 0.22315495 0.12908554]
(1008,)
------
21
[2.51323962 1.98924065 1.47266853 ... 0.21820366 0.1215653  0.40903744]
(1056,)
------
22
[2.51323962 1.98924065 1.47266853 ... 0.10070082 0.38809934 1.00548422]
(1104,)
------
23
[2.51323962 1.98924065 1.47266853 ... 0.4266322  1.05441153 1.66616738]
(1152,)
------
24
[2.51323962 1.98924065 1.47266853 ... 1.04552901 1.65498006 2.18023109]
(1200,)
------
25
[2.51323962 1.98924065 1.47266853 ... 1.65543401 2.18637466 2.63329387]
(1248,)
------
26
[2.51323962 1.98924065 1.47266853 ... 2.19168305 2.64080548 2.81173015]
(1296,)
------
27
[2.51323962 1.98924065 1.47266853 ... 2.64069057 2.80696559 2.58723164]
(1344,)
------
28
[2.51323962 1.98924065 1.47266853 ... 2.80788422 2.5843637  2.01216269]
(1392,)
------
29
[2.51323962 1.98924065 1.47266853 ... 2.58965516 2.02567959 1.50233698]
(1440,)
------
30
[2.51323962 1.98924065 1.47266853 ... 1.97934532 1.45393002 0.975806  ]
(1488,)
------
31
[2.5132396

[2.51323962 1.98924065 1.47266853 ... 1.32271993 1.69458544 2.02523065]
(5376,)
------
112
[2.51323962 1.98924065 1.47266853 ... 1.69828975 2.02618289 2.23835588]
(5424,)
------
113
[2.51323962 1.98924065 1.47266853 ... 2.05756879 2.25476718 2.18013763]
(5472,)
------
114
[2.51323962 1.98924065 1.47266853 ... 2.25410676 2.16389585 1.76501751]
(5520,)
------
115
[2.51323962 1.98924065 1.47266853 ... 2.17238832 1.78792858 1.35266793]
(5568,)
------
116
[2.51323962 1.98924065 1.47266853 ... 1.79587305 1.35716736 0.93137789]
(5616,)
------
117
[2.51323962 1.98924065 1.47266853 ... 1.33757079 0.89760041 0.43336472]
(5664,)
------
118
[2.51323962 1.98924065 1.47266853 ... 0.84078646 0.36101875 0.03105068]
(5712,)
------
119
[ 2.51323962  1.98924065  1.47266853 ...  0.32326481 -0.02370012
 -0.08546197]
(5760,)
------
120
[ 2.51323962  1.98924065  1.47266853 ... -0.04504184 -0.10786553
  0.21769744]
(5808,)
------
121
[ 2.51323962  1.98924065  1.47266853 ... -0.13716833  0.21510237
  0.8268173

[2.51323962 1.98924065 1.47266853 ... 1.96470845 1.47254372 1.04257953]
(9840,)
------
205
[2.51323962 1.98924065 1.47266853 ... 1.45894468 1.01768839 0.59031677]
(9888,)
------
206
[2.51323962 1.98924065 1.47266853 ... 0.96169251 0.52046037 0.20823164]
(9936,)
------
207
[2.51323962 1.98924065 1.47266853 ... 0.52317762 0.21311398 0.17542146]
(9984,)
------
208
[2.51323962 1.98924065 1.47266853 ... 0.18124472 0.15151434 0.46362916]
(10032,)
------
209
[2.51323962 1.98924065 1.47266853 ... 0.13048249 0.43868947 0.98255634]
(10080,)
------
210
[2.51323962 1.98924065 1.47266853 ... 0.4525125  0.98966694 1.46902788]
(10128,)
------
211
[2.51323962 1.98924065 1.47266853 ... 0.99948674 1.48702431 1.932302  ]
(10176,)
------
212
[2.51323962 1.98924065 1.47266853 ... 1.49564266 1.9494983  2.33901572]
(10224,)
------
213
[2.51323962 1.98924065 1.47266853 ... 1.93905222 2.33629584 2.50968194]
(10272,)
------
214
[2.51323962 1.98924065 1.47266853 ... 2.31873775 2.49815249 2.31419635]
(10320,)
---

[2.51323962 1.98924065 1.47266853 ... 1.63560259 1.02791178 0.48640117]
(14064,)
------
293
[ 2.51323962  1.98924065  1.47266853 ...  1.00422752  0.45300993
 -0.06197774]
(14112,)
------
294
[ 2.51323962  1.98924065  1.47266853 ...  0.42851552 -0.08712069
 -0.35847053]
(14160,)
------
295
[ 2.51323962  1.98924065  1.47266853 ... -0.08324073 -0.34584689
 -0.16636401]
(14208,)
------
296
[ 2.51323962  1.98924065  1.47266853 ... -0.34186029 -0.16871928
  0.41719595]
(14256,)
------
297
[ 2.51323962  1.98924065  1.47266853 ... -0.18100037  0.4104304
  1.03562546]
(14304,)
------
298
[2.51323962 1.98924065 1.47266853 ... 0.39574543 1.02112198 1.55914259]
(14352,)
------
299
[2.51323962 1.98924065 1.47266853 ... 1.03795433 1.58018458 2.05904031]
(14400,)
------
300
[2.51323962 1.98924065 1.47266853 ... 1.58910525 2.0758636  2.29474616]
(14448,)
------
301
[2.51323962 1.98924065 1.47266853 ... 2.08263707 2.31451058 2.13158917]
(14496,)
------
302
[2.51323962 1.98924065 1.47266853 ... 2.319170

[ 2.51323962  1.98924065  1.47266853 ...  0.64225453  0.06747067
 -0.31495667]
(18288,)
------
381
[ 2.51323962  1.98924065  1.47266853 ...  0.10874899 -0.28244421
 -0.31999639]
(18336,)
------
382
[ 2.51323962  1.98924065  1.47266853 ... -0.27108091 -0.3076092
  0.11497748]
(18384,)
------
383
[ 2.51323962  1.98924065  1.47266853 ... -0.33639789  0.10338086
  0.80525762]
(18432,)
------
384
[2.51323962 1.98924065 1.47266853 ... 0.10397337 0.81033832 1.43824661]
(18480,)
------
385
[2.51323962 1.98924065 1.47266853 ... 0.79197913 1.41901791 1.99316084]
(18528,)
------
386
[2.51323962 1.98924065 1.47266853 ... 1.44174993 2.02428651 2.46887422]
(18576,)
------
387
[2.51323962 1.98924065 1.47266853 ... 2.03468251 2.48346639 2.63188291]
(18624,)
------
388
[2.51323962 1.98924065 1.47266853 ... 2.47529387 2.61395812 2.29840136]
(18672,)
------
389
[2.51323962 1.98924065 1.47266853 ... 2.58854222 2.2610414  1.62462866]
(18720,)
------
390
[2.51323962 1.98924065 1.47266853 ... 2.24166608 1.61

[2.51323962 1.98924065 1.47266853 ... 0.51465201 0.33230093 0.42666674]
(22512,)
------
469
[2.51323962 1.98924065 1.47266853 ... 0.31737682 0.41684151 0.77248478]
(22560,)
------
470
[2.51323962 1.98924065 1.47266853 ... 0.43121067 0.7907837  1.21942794]
(22608,)
------
471
[2.51323962 1.98924065 1.47266853 ... 0.80526036 1.23100507 1.59202969]
(22656,)
------
472
[2.51323962 1.98924065 1.47266853 ... 1.22721946 1.58830702 1.93390214]
(22704,)
------
473
[2.51323962 1.98924065 1.47266853 ... 1.59648716 1.95027697 2.15898013]
(22752,)
------
474
[2.51323962 1.98924065 1.47266853 ... 1.94851553 2.1619308  2.0895462 ]
(22800,)
------
475
[2.51323962 1.98924065 1.47266853 ... 2.17358947 2.0986619  1.72843969]
(22848,)
------
476
[2.51323962 1.98924065 1.47266853 ... 2.09553027 1.73515093 1.33337343]
(22896,)
------
477
[2.51323962 1.98924065 1.47266853 ... 1.76077974 1.36435759 0.99071449]
(22944,)
------
478
[2.51323962 1.98924065 1.47266853 ... 1.37057412 1.00313342 0.63319755]
(22992,)

[2.51323962 1.98924065 1.47266853 ... 1.05639124 1.39622307 1.69172919]
(26880,)
------
560
[2.51323962 1.98924065 1.47266853 ... 1.38769662 1.68075788 1.89888847]
(26928,)
------
561
[2.51323962 1.98924065 1.47266853 ... 1.68595397 1.90702248 1.94725001]
(26976,)
------
562
[2.51323962 1.98924065 1.47266853 ... 1.92803299 1.97264826 1.74916744]
(27024,)
------
563
[2.51323962 1.98924065 1.47266853 ... 1.95424688 1.72485316 1.35690939]
(27072,)
------
564
[2.51323962 1.98924065 1.47266853 ... 1.70361996 1.3278507  0.97946948]
(27120,)
------
565
[2.51323962 1.98924065 1.47266853 ... 1.3337574  0.97440892 0.59286624]
(27168,)
------
566
[2.51323962 1.98924065 1.47266853 ... 0.94684887 0.55368352 0.23034708]
(27216,)
------
567
[2.51323962 1.98924065 1.47266853 ... 0.55924171 0.2372247  0.1202726 ]
(27264,)
------
568
[2.51323962 1.98924065 1.47266853 ... 0.22259413 0.11548982 0.25120679]
(27312,)
------
569
[2.51323962 1.98924065 1.47266853 ... 0.11658746 0.25107321 0.6308763 ]
(27360,)

[2.51323962 1.98924065 1.47266853 ... 2.17445636 1.69007587 1.27414203]
(31296,)
------
652
[2.51323962 1.98924065 1.47266853 ... 1.70663106 1.28315341 0.85933661]
(31344,)
------
653
[2.51323962 1.98924065 1.47266853 ... 1.27075207 0.84192604 0.50338387]
(31392,)
------
654
[2.51323962 1.98924065 1.47266853 ... 0.79525489 0.45731178 0.39917544]
(31440,)
------
655
[2.51323962 1.98924065 1.47266853 ... 0.4539679  0.40285453 0.71446377]
(31488,)
------
656
[2.51323962 1.98924065 1.47266853 ... 0.38827491 0.7042678  1.21631896]
(31536,)
------
657
[2.51323962 1.98924065 1.47266853 ... 0.70505482 1.21845973 1.65269291]
(31584,)
------
658
[2.51323962 1.98924065 1.47266853 ... 1.21397901 1.64990008 2.05519938]
(31632,)
------
659
[2.51323962 1.98924065 1.47266853 ... 1.65956128 2.06647444 2.33520293]
(31680,)
------
660
[2.51323962 1.98924065 1.47266853 ... 2.05449009 2.31561542 2.31208682]
(31728,)
------
661
[2.51323962 1.98924065 1.47266853 ... 2.32389498 2.32055712 1.98540938]
(31776,)

[2.51323962 1.98924065 1.47266853 ... 0.3363564  0.14678161 0.3408345 ]
(35616,)
------
742
[2.51323962 1.98924065 1.47266853 ... 0.18475616 0.37346241 0.9418748 ]
(35664,)
------
743
[2.51323962 1.98924065 1.47266853 ... 0.40742865 0.98241109 1.61995828]
(35712,)
------
744
[2.51323962 1.98924065 1.47266853 ... 0.98725623 1.63568795 2.19826627]
(35760,)
------
745
[2.51323962 1.98924065 1.47266853 ... 1.67943799 2.25947762 2.77837181]
(35808,)
------
746
[2.51323962 1.98924065 1.47266853 ... 2.33805275 2.87020111 3.15257668]
(35856,)
------
747
[2.51323962 1.98924065 1.47266853 ... 2.88886189 3.17890239 3.12007642]
(35904,)
------
748
[2.51323962 1.98924065 1.47266853 ... 3.18717694 3.10689545 2.54926658]
(35952,)
------
749
[2.51323962 1.98924065 1.47266853 ... 3.10023689 2.56091285 1.89977992]
(36000,)
------
750
[2.51323962 1.98924065 1.47266853 ... 2.56646895 1.91426909 1.39355385]
(36048,)
------
751
[2.51323962 1.98924065 1.47266853 ... 1.90684497 1.3861233  0.90047342]
(36096,)

[2.51323962 1.98924065 1.47266853 ... 2.01898217 2.43217373 2.64949656]
(40032,)
------
834
[2.51323962 1.98924065 1.47266853 ... 2.43109989 2.6460135  2.52411509]
(40080,)
------
835
[2.51323962 1.98924065 1.47266853 ... 2.64970851 2.53845    2.11565137]
(40128,)
------
836
[2.51323962 1.98924065 1.47266853 ... 2.50896454 2.09816384 1.65911376]
(40176,)
------
837
[2.51323962 1.98924065 1.47266853 ... 2.09901071 1.65988159 1.22298813]
(40224,)
------
838
[2.51323962 1.98924065 1.47266853 ... 1.64445257 1.19711733 0.72564954]
(40272,)
------
839
[2.51323962 1.98924065 1.47266853 ... 1.16660249 0.68330127 0.38212729]
(40320,)
------
840
[2.51323962 1.98924065 1.47266853 ... 0.70739222 0.39731559 0.41682363]
(40368,)
------
841
[2.51323962 1.98924065 1.47266853 ... 0.37487003 0.38199428 0.7733646 ]
(40416,)
------
842
[2.51323962 1.98924065 1.47266853 ... 0.3752276  0.7495026  1.3382926 ]
(40464,)
------
843
[2.51323962 1.98924065 1.47266853 ... 0.75146961 1.33448255 1.86752117]
(40512,)

[2.51323962 1.98924065 1.47266853 ... 2.54417419 2.02786326 1.49662054]
(44400,)
------
925
[2.51323962 1.98924065 1.47266853 ... 2.03068042 1.49678481 0.99104375]
(44448,)
------
926
[2.51323962 1.98924065 1.47266853 ... 1.50392282 0.99104691 0.52224237]
(44496,)
------
927
[2.51323962 1.98924065 1.47266853 ... 0.98011333 0.505876   0.23737399]
(44544,)
------
928
[2.51323962 1.98924065 1.47266853 ... 0.49713835 0.2403814  0.35411277]
(44592,)
------
929
[2.51323962 1.98924065 1.47266853 ... 0.24654771 0.34779969 0.85657692]
(44640,)
------
930
[2.51323962 1.98924065 1.47266853 ... 0.35912001 0.87159324 1.47782147]
(44688,)
------
931
[2.51323962 1.98924065 1.47266853 ... 0.86052275 1.47379434 2.02658296]
(44736,)
------
932
[2.51323962 1.98924065 1.47266853 ... 1.48926508 2.0553844  2.58348823]
(44784,)
------
933
[2.51323962 1.98924065 1.47266853 ... 2.08476067 2.63153434 2.98640943]
(44832,)
------
934
[2.51323962 1.98924065 1.47266853 ... 2.63136029 2.99846554 3.02725673]
(44880,)

[2.51323962 1.98924065 1.47266853 ... 1.9898504  1.36667502 0.82349688]
(48624,)
------
1013
[2.51323962 1.98924065 1.47266853 ... 1.38035619 0.82454258 0.27751935]
(48672,)
------
1014
[ 2.51323962  1.98924065  1.47266853 ...  0.82203048  0.27236375
 -0.14677496]
(48720,)
------
1015
[ 2.51323962  1.98924065  1.47266853 ...  0.25034109 -0.16254212
 -0.17568247]
(48768,)
------
1016
[ 2.51323962  1.98924065  1.47266853 ... -0.18069653 -0.17643523
  0.31896031]
(48816,)
------
1017
[ 2.51323962  1.98924065  1.47266853 ... -0.13264523  0.35500011
  1.02275479]
(48864,)
------
1018
[2.51323962 1.98924065 1.47266853 ... 0.3479906  1.01265156 1.55678797]
(48912,)
------
1019
[2.51323962 1.98924065 1.47266853 ... 1.01613867 1.56469476 2.06824112]
(48960,)
------
1020
[2.51323962 1.98924065 1.47266853 ... 1.59516847 2.10562611 2.41574407]
(49008,)
------
1021
[2.51323962 1.98924065 1.47266853 ... 2.09832358 2.42319751 2.40464711]
(49056,)
------
1022
[2.51323962 1.98924065 1.47266853 ... 2.43

[2.51323962 1.98924065 1.47266853 ... 1.58080399 1.11109841 0.62734318]
(52800,)
------
1100
[2.51323962 1.98924065 1.47266853 ... 1.12657797 0.64306635 0.21069275]
(52848,)
------
1101
[2.51323962 1.98924065 1.47266853 ... 0.66476363 0.22844392 0.04428768]
(52896,)
------
1102
[2.51323962 1.98924065 1.47266853 ... 0.25956693 0.07250682 0.24306917]
(52944,)
------
1103
[2.51323962 1.98924065 1.47266853 ... 0.07353622 0.24386571 0.75932091]
(52992,)
------
1104
[2.51323962 1.98924065 1.47266853 ... 0.26587966 0.78618002 1.36243999]
(53040,)
------
1105
[2.51323962 1.98924065 1.47266853 ... 0.78401881 1.36162913 1.88291895]
(53088,)
------
1106
[2.51323962 1.98924065 1.47266853 ... 1.37525165 1.90365314 2.3745575 ]
(53136,)
------
1107
[2.51323962 1.98924065 1.47266853 ... 1.94853878 2.42976356 2.68372822]
(53184,)
------
1108
[2.51323962 1.98924065 1.47266853 ... 2.41734409 2.66386008 2.55724263]
(53232,)
------
1109
[2.51323962 1.98924065 1.47266853 ... 2.6638844  2.53512287 2.00290751

[2.51323962 1.98924065 1.47266853 ... 0.12435526 0.16412981 0.49162292]
(57120,)
------
1190
[2.51323962 1.98924065 1.47266853 ... 0.18818389 0.51055205 0.94633085]
(57168,)
------
1191
[2.51323962 1.98924065 1.47266853 ... 0.54330343 0.96521163 1.30215812]
(57216,)
------
1192
[2.51323962 1.98924065 1.47266853 ... 0.94175822 1.28666461 1.61544287]
(57264,)
------
1193
[2.51323962 1.98924065 1.47266853 ... 1.29014933 1.63055861 1.85630167]
(57312,)
------
1194
[2.51323962 1.98924065 1.47266853 ... 1.62487698 1.84186494 1.81536007]
(57360,)
------
1195
[2.51323962 1.98924065 1.47266853 ... 1.84968185 1.81604111 1.52266181]
(57408,)
------
1196
[2.51323962 1.98924065 1.47266853 ... 1.81459272 1.52690029 1.18029058]
(57456,)
------
1197
[2.51323962 1.98924065 1.47266853 ... 1.53203928 1.18780494 0.85335022]
(57504,)
------
1198
[2.51323962 1.98924065 1.47266853 ... 1.17321825 0.83439922 0.48351493]
(57552,)
------
1199
[2.51323962 1.98924065 1.47266853 ... 0.82501823 0.46994779 0.24025412

[2.51323962 1.98924065 1.47266853 ... 1.84479749 2.01485825 1.98108101]
(61536,)
------
1282
[2.51323962 1.98924065 1.47266853 ... 2.02648616 1.99586618 1.72397852]
(61584,)
------
1283
[2.51323962 1.98924065 1.47266853 ... 1.97759306 1.70028436 1.32948279]
(61632,)
------
1284
[2.51323962 1.98924065 1.47266853 ... 1.70432794 1.32829082 0.96728182]
(61680,)
------
1285
[2.51323962 1.98924065 1.47266853 ... 1.33279407 0.96385866 0.5707584 ]
(61728,)
------
1286
[2.51323962 1.98924065 1.47266853 ... 0.93133879 0.52362615 0.22752655]
(61776,)
------
1287
[2.51323962 1.98924065 1.47266853 ... 0.52932924 0.22604942 0.16179006]
(61824,)
------
1288
[2.51323962 1.98924065 1.47266853 ... 0.23707862 0.17308603 0.34081388]
(61872,)
------
1289
[2.51323962 1.98924065 1.47266853 ... 0.18192856 0.33382416 0.73706323]
(61920,)
------
1290
[2.51323962 1.98924065 1.47266853 ... 0.35603157 0.75303525 1.17443311]
(61968,)
------
1291
[2.51323962 1.98924065 1.47266853 ... 0.74787456 1.16779578 1.5192591 

[2.51323962 1.98924065 1.47266853 ... 2.09442973 1.57021177 1.08704233]
(65856,)
------
1372
[2.51323962 1.98924065 1.47266853 ... 1.57311106 1.08541381 0.63467735]
(65904,)
------
1373
[2.51323962 1.98924065 1.47266853 ... 1.07677138 0.6231696  0.22794563]
(65952,)
------
1374
[2.51323962 1.98924065 1.47266853 ... 0.6251772  0.22792183 0.10618192]
(66000,)
------
1375
[2.51323962 1.98924065 1.47266853 ... 0.23721917 0.12539858 0.43175423]
(66048,)
------
1376
[2.51323962 1.98924065 1.47266853 ... 0.13333528 0.44721791 0.99595886]
(66096,)
------
1377
[2.51323962 1.98924065 1.47266853 ... 0.42452466 0.9743802  1.46309125]
(66144,)
------
1378
[2.51323962 1.98924065 1.47266853 ... 0.96337432 1.45837724 1.90927112]
(66192,)
------
1379
[2.51323962 1.98924065 1.47266853 ... 1.49272525 1.95110703 2.25569773]
(66240,)
------
1380
[2.51323962 1.98924065 1.47266853 ... 1.94852102 2.25472617 2.28450871]
(66288,)
------
1381
[2.51323962 1.98924065 1.47266853 ... 2.24571323 2.27424502 1.95533264

[ 2.51323962  1.98924065  1.47266853 ...  1.12435377  0.55511522
 -0.02795353]
(70032,)
------
1459
[ 2.51323962  1.98924065  1.47266853 ...  0.49121365 -0.11984527
 -0.70927233]
(70080,)
------
1460
[ 2.51323962  1.98924065  1.47266853 ... -0.15239906 -0.75599074
 -1.02535093]
(70128,)
------
1461
[ 2.51323962  1.98924065  1.47266853 ... -0.79591507 -1.08903158
 -0.97632295]
(70176,)
------
1462
[ 2.51323962  1.98924065  1.47266853 ... -1.13505733 -1.00721896
 -0.41313002]
(70224,)
------
1463
[ 2.51323962  1.98924065  1.47266853 ... -1.00780976 -0.43748179
  0.28747931]
(70272,)
------
1464
[ 2.51323962  1.98924065  1.47266853 ... -0.44179019  0.26915231
  0.8607102 ]
(70320,)
------
1465
[2.51323962 1.98924065 1.47266853 ... 0.25557476 0.85243446 1.42375958]
(70368,)
------
1466
[2.51323962 1.98924065 1.47266853 ... 0.8485468  1.42220342 1.84835732]
(70416,)
------
1467
[2.51323962 1.98924065 1.47266853 ... 1.44412673 1.90052605 2.02969337]
(70464,)
------
1468
[2.51323962 1.9892406

[2.51323962 1.98924065 1.47266853 ... 2.14802957 2.10443878 1.69139445]
(74112,)
------
1544
[2.51323962 1.98924065 1.47266853 ... 2.10140133 1.70310163 1.14509237]
(74160,)
------
1545
[2.51323962 1.98924065 1.47266853 ... 1.69873142 1.14581382 0.64491194]
(74208,)
------
1546
[2.51323962 1.98924065 1.47266853 ... 1.15143144 0.65008682 0.12684101]
(74256,)
------
1547
[ 2.51323962  1.98924065  1.47266853 ...  0.65827107  0.12877847
 -0.31323764]
(74304,)
------
1548
[ 2.51323962  1.98924065  1.47266853 ...  0.120703   -0.3270219
 -0.48957279]
(74352,)
------
1549
[ 2.51323962  1.98924065  1.47266853 ... -0.31824768 -0.46578217
 -0.14890571]
(74400,)
------
1550
[ 2.51323962  1.98924065  1.47266853 ... -0.44399557 -0.13134366
  0.49489698]
(74448,)
------
1551
[ 2.51323962  1.98924065  1.47266853 ... -0.09972081  0.52238458
  1.10353971]
(74496,)
------
1552
[2.51323962 1.98924065 1.47266853 ... 0.49658343 1.09096897 1.62611914]
(74544,)
------
1553
[2.51323962 1.98924065 1.47266853 ..

[2.51323962 1.98924065 1.47266853 ... 1.52993095 1.89593446 1.97766745]
(78288,)
------
1631
[2.51323962 1.98924065 1.47266853 ... 1.90110457 1.98212719 1.69848025]
(78336,)
------
1632
[2.51323962 1.98924065 1.47266853 ... 1.98430634 1.70417452 1.17844081]
(78384,)
------
1633
[2.51323962 1.98924065 1.47266853 ... 1.73221719 1.19856703 0.6770184 ]
(78432,)
------
1634
[2.51323962 1.98924065 1.47266853 ... 1.21245587 0.68051451 0.19308288]
(78480,)
------
1635
[ 2.51323962  1.98924065  1.47266853 ...  0.67424583  0.18616904
 -0.1554058 ]
(78528,)
------
1636
[ 2.51323962  1.98924065  1.47266853 ...  0.21912868 -0.12120997
 -0.22211301]
(78576,)
------
1637
[ 2.51323962  1.98924065  1.47266853 ... -0.11178291 -0.21469943
  0.06317035]
(78624,)
------
1638
[ 2.51323962  1.98924065  1.47266853 ... -0.22563218  0.04664032
  0.59258467]
(78672,)
------
1639
[2.51323962 1.98924065 1.47266853 ... 0.02963694 0.56729811 1.0353508 ]
(78720,)
------
1640
[2.51323962 1.98924065 1.47266853 ... 0.55

[2.51323962 1.98924065 1.47266853 ... 1.71118164 1.94823968 1.88471985]
(82464,)
------
1718
[2.51323962 1.98924065 1.47266853 ... 1.95023859 1.86977851 1.36887395]
(82512,)
------
1719
[2.51323962 1.98924065 1.47266853 ... 1.89258778 1.38373125 0.76919174]
(82560,)
------
1720
[2.51323962 1.98924065 1.47266853 ... 1.40073836 0.78073806 0.24799697]
(82608,)
------
1721
[ 2.51323962  1.98924065  1.47266853 ...  0.76701325  0.22214673
 -0.30395684]
(82656,)
------
1722
[ 2.51323962  1.98924065  1.47266853 ...  0.19812828 -0.33831397
 -0.67739564]
(82704,)
------
1723
[ 2.51323962  1.98924065  1.47266853 ... -0.35356572 -0.69474167
 -0.65022063]
(82752,)
------
1724
[ 2.51323962  1.98924065  1.47266853 ... -0.67648697 -0.63038152
 -0.152833  ]
(82800,)
------
1725
[ 2.51323962  1.98924065  1.47266853 ... -0.6256128  -0.16198844
  0.50004679]
(82848,)
------
1726
[ 2.51323962  1.98924065  1.47266853 ... -0.17371058  0.48348817
  1.07281935]
(82896,)
------
1727
[2.51323962 1.98924065 1.472

[2.51323962 1.98924065 1.47266853 ... 1.59483063 1.99370301 2.09708023]
(86592,)
------
1804
[2.51323962 1.98924065 1.47266853 ... 1.99033725 2.09771085 1.7985878 ]
(86640,)
------
1805
[2.51323962 1.98924065 1.47266853 ... 2.10097289 1.79809201 1.19575644]
(86688,)
------
1806
[2.51323962 1.98924065 1.47266853 ... 1.80268288 1.20422745 0.70368856]
(86736,)
------
1807
[2.51323962 1.98924065 1.47266853 ... 1.2112999  0.71196961 0.28002763]
(86784,)
------
1808
[ 2.51323962  1.98924065  1.47266853 ...  0.70613146  0.2733227
 -0.11319796]
(86832,)
------
1809
[ 2.51323962  1.98924065  1.47266853 ...  0.25841314 -0.12259003
 -0.25272593]
(86880,)
------
1810
[ 2.51323962  1.98924065  1.47266853 ... -0.1035369  -0.22721107
  0.03446283]
(86928,)
------
1811
[ 2.51323962  1.98924065  1.47266853 ... -0.22903226  0.0343172
  0.55028248]
(86976,)
------
1812
[2.51323962 1.98924065 1.47266853 ... 0.03476386 0.5491963  1.03911424]
(87024,)
------
1813
[2.51323962 1.98924065 1.47266853 ... 0.5468

[2.51323962 1.98924065 1.47266853 ... 1.40443766 1.6950084  1.84931755]
(90720,)
------
1890
[2.51323962 1.98924065 1.47266853 ... 1.69721079 1.83615267 1.69169247]
(90768,)
------
1891
[2.51323962 1.98924065 1.47266853 ... 1.82324219 1.67990112 1.28063202]
(90816,)
------
1892
[2.51323962 1.98924065 1.47266853 ... 1.69543135 1.30126786 0.9096759 ]
(90864,)
------
1893
[2.51323962 1.98924065 1.47266853 ... 1.30495334 0.90853161 0.54766577]
(90912,)
------
1894
[2.51323962 1.98924065 1.47266853 ... 0.91360265 0.54969651 0.2064061 ]
(90960,)
------
1895
[2.51323962 1.98924065 1.47266853 ... 0.54489648 0.19929485 0.01164542]
(91008,)
------
1896
[ 2.51323962e+00  1.98924065e+00  1.47266853e+00 ...  1.84641242e-01
 -1.88416243e-03  1.05186462e-01]
(91056,)
------
1897
[ 2.51323962  1.98924065  1.47266853 ... -0.0093444   0.09330779
  0.4804157 ]
(91104,)
------
1898
[2.51323962 1.98924065 1.47266853 ... 0.096506   0.46651065 0.94689864]
(91152,)
------
1899
[2.51323962 1.98924065 1.4726685

[2.51323962 1.98924065 1.47266853 ... 1.73165226 1.38794172 1.04950774]
(95040,)
------
1980
[2.51323962 1.98924065 1.47266853 ... 1.40082633 1.05785549 0.67747134]
(95088,)
------
1981
[2.51323962 1.98924065 1.47266853 ... 1.03487885 0.64500332 0.29829702]
(95136,)
------
1982
[2.51323962 1.98924065 1.47266853 ... 0.62757605 0.29307762 0.15409416]
(95184,)
------
1983
[2.51323962 1.98924065 1.47266853 ... 0.31211188 0.18136026 0.28143373]
(95232,)
------
1984
[2.51323962 1.98924065 1.47266853 ... 0.17931278 0.29650173 0.62974453]
(95280,)
------
1985
[2.51323962 1.98924065 1.47266853 ... 0.30026084 0.64150411 1.05834746]
(95328,)
------
1986
[2.51323962 1.98924065 1.47266853 ... 0.65978289 1.06715631 1.39844286]
(95376,)
------
1987
[2.51323962 1.98924065 1.47266853 ... 1.05528748 1.39079762 1.68935049]
(95424,)
------
1988
[2.51323962 1.98924065 1.47266853 ... 1.38740063 1.69110739 1.89852524]
(95472,)
------
1989
[2.51323962 1.98924065 1.47266853 ... 1.68688309 1.90072119 1.89306319

[2.51323962 1.98924065 1.47266853 ... 1.95375454 1.41035092 0.92094707]
(99264,)
------
2068
[2.51323962 1.98924065 1.47266853 ... 1.40698302 0.9171415  0.47699094]
(99312,)
------
2069
[2.51323962 1.98924065 1.47266853 ... 0.91741198 0.47966266 0.19824255]
(99360,)
------
2070
[2.51323962 1.98924065 1.47266853 ... 0.5122602  0.22232537 0.30412659]
(99408,)
------
2071
[2.51323962 1.98924065 1.47266853 ... 0.21089841 0.28781989 0.74885583]
(99456,)
------
2072
[2.51323962 1.98924065 1.47266853 ... 0.27581933 0.73384362 1.30257785]
(99504,)
------
2073
[2.51323962 1.98924065 1.47266853 ... 0.70315665 1.27392972 1.72918701]
(99552,)
------
2074
[2.51323962 1.98924065 1.47266853 ... 1.2739352  1.73278439 2.14258981]
(99600,)
------
2075
[2.51323962 1.98924065 1.47266853 ... 1.71539116 2.11800575 2.33260798]
(99648,)
------
2076
[2.51323962 1.98924065 1.47266853 ... 2.1099968  2.32439256 2.26353812]
(99696,)
------
2077
[2.51323962 1.98924065 1.47266853 ... 2.31125975 2.22866035 1.75990427

[2.51323962 1.98924065 1.47266853 ... 2.0048902  1.32764816 0.64321738]
(103392,)
------
2154
[ 2.51323962  1.98924065  1.47266853 ...  1.31992435  0.60767198
 -0.0616979 ]
(103440,)
------
2155
[ 2.51323962  1.98924065  1.47266853 ...  0.54872739 -0.15239149
 -0.69332838]
(103488,)
------
2156
[ 2.51323962  1.98924065  1.47266853 ... -0.22032075 -0.77040148
 -0.92815655]
(103536,)
------
2157
[ 2.51323962  1.98924065  1.47266853 ... -0.7562831  -0.92333412
 -0.62349176]
(103584,)
------
2158
[ 2.51323962  1.98924065  1.47266853 ... -0.9079991  -0.63779134
  0.06412786]
(103632,)
------
2159
[ 2.51323962  1.98924065  1.47266853 ... -0.64816946  0.02956915
  0.84392577]
(103680,)
------
2160
[ 2.51323962  1.98924065  1.47266853 ... -0.01145898  0.79871774
  1.46791589]
(103728,)
------
2161
[2.51323962 1.98924065 1.47266853 ... 0.78812879 1.45649111 2.06867313]
(103776,)
------
2162
[2.51323962 1.98924065 1.47266853 ... 1.46717775 2.08658099 2.49776292]
(103824,)
------
2163
[2.51323962

[2.51323962 1.98924065 1.47266853 ... 1.76259422 1.98763716 1.85161483]
(107472,)
------
2239
[2.51323962 1.98924065 1.47266853 ... 1.98721468 1.86414528 1.373209  ]
(107520,)
------
2240
[2.51323962 1.98924065 1.47266853 ... 1.85461366 1.35731506 0.77347827]
(107568,)
------
2241
[2.51323962 1.98924065 1.47266853 ... 1.35270631 0.77007169 0.23398857]
(107616,)
------
2242
[ 2.51323962  1.98924065  1.47266853 ...  0.77112645  0.22882251
 -0.33419785]
(107664,)
------
2243
[ 2.51323962  1.98924065  1.47266853 ...  0.17842686 -0.39493498
 -0.75811368]
(107712,)
------
2244
[ 2.51323962  1.98924065  1.47266853 ... -0.41136995 -0.77652788
 -0.8242293 ]
(107760,)
------
2245
[ 2.51323962  1.98924065  1.47266853 ... -0.76046848 -0.8007614
 -0.4589583 ]
(107808,)
------
2246
[ 2.51323962  1.98924065  1.47266853 ... -0.81714696 -0.4797934
  0.15199542]
(107856,)
------
2247
[ 2.51323962  1.98924065  1.47266853 ... -0.41435942  0.21793462
  0.82141083]
(107904,)
------
2248
[2.51323962 1.989240

[2.51323962 1.98924065 1.47266853 ... 1.67439592 2.07831311 2.3152082 ]
(111648,)
------
2326
[2.51323962 1.98924065 1.47266853 ... 2.06381917 2.32151723 2.28158665]
(111696,)
------
2327
[2.51323962 1.98924065 1.47266853 ... 2.30226445 2.26109242 1.88519478]
(111744,)
------
2328
[2.51323962 1.98924065 1.47266853 ... 2.19271255 1.83220971 1.37076914]
(111792,)
------
2329
[2.51323962 1.98924065 1.47266853 ... 1.817729   1.37033463 0.95695573]
(111840,)
------
2330
[2.51323962 1.98924065 1.47266853 ... 1.36723518 0.95287007 0.60336077]
(111888,)
------
2331
[2.51323962 1.98924065 1.47266853 ... 0.93116695 0.58176827 0.38011169]
(111936,)
------
2332
[2.51323962 1.98924065 1.47266853 ... 0.57957458 0.37129429 0.41314903]
(111984,)
------
2333
[2.51323962 1.98924065 1.47266853 ... 0.37928519 0.42094406 0.77358752]
(112032,)
------
2334
[2.51323962 1.98924065 1.47266853 ... 0.43093908 0.78300029 1.24568141]
(112080,)
------
2335
[2.51323962 1.98924065 1.47266853 ... 0.7733714  1.23577893 

[2.51323962 1.98924065 1.47266853 ... 2.08722496 2.23585963 2.03853774]
(115872,)
------
2414
[2.51323962 1.98924065 1.47266853 ... 2.24540496 2.032161   1.47459316]
(115920,)
------
2415
[2.51323962 1.98924065 1.47266853 ... 2.05673528 1.49095666 0.92747349]
(115968,)
------
2416
[2.51323962 1.98924065 1.47266853 ... 1.50572586 0.93639022 0.42975822]
(116016,)
------
2417
[ 2.51323962  1.98924065  1.47266853 ...  0.93269604  0.41483709
 -0.05219807]
(116064,)
------
2418
[ 2.51323962  1.98924065  1.47266853 ...  0.4106673  -0.06121033
 -0.26527059]
(116112,)
------
2419
[ 2.51323962  1.98924065  1.47266853 ... -0.0290368  -0.23338515
 -0.03011318]
(116160,)
------
2420
[ 2.51323962  1.98924065  1.47266853 ... -0.20677419 -0.01008572
  0.55831552]
(116208,)
------
2421
[2.51323962 1.98924065 1.47266853 ... 0.01367867 0.57517749 1.21328568]
(116256,)
------
2422
[2.51323962 1.98924065 1.47266853 ... 0.56655401 1.20750844 1.73095644]
(116304,)
------
2423
[2.51323962 1.98924065 1.4726685

[2.51323962 1.98924065 1.47266853 ... 2.39291668 2.29874897 1.80210304]
(120048,)
------
2501
[2.51323962 1.98924065 1.47266853 ... 2.27887249 1.78377759 1.22350037]
(120096,)
------
2502
[2.51323962 1.98924065 1.47266853 ... 1.79085267 1.23366868 0.78017789]
(120144,)
------
2503
[2.51323962 1.98924065 1.47266853 ... 1.22756088 0.77332705 0.33935437]
(120192,)
------
2504
[2.51323962 1.98924065 1.47266853 ... 0.76059705 0.32555035 0.02402224]
(120240,)
------
2505
[ 2.51323962  1.98924065  1.47266853 ...  0.28948706 -0.00622127
  0.01994862]
(120288,)
------
2506
[ 2.51323962  1.98924065  1.47266853 ... -0.00683331  0.02711344
  0.4455719 ]
(120336,)
------
2507
[2.51323962 1.98924065 1.47266853 ... 0.01948349 0.43404663 0.98405552]
(120384,)
------
2508
[2.51323962 1.98924065 1.47266853 ... 0.41605854 0.96835375 1.42489946]
(120432,)
------
2509
[2.51323962 1.98924065 1.47266853 ... 0.95953703 1.41690791 1.81942749]
(120480,)
------
2510
[2.51323962 1.98924065 1.47266853 ... 1.431664

[2.51323962 1.98924065 1.47266853 ... 1.86700284 1.55731678 1.11156595]
(124224,)
------
2588
[2.51323962 1.98924065 1.47266853 ... 1.57505357 1.12828147 0.74207491]
(124272,)
------
2589
[2.51323962 1.98924065 1.47266853 ... 1.13040161 0.74138457 0.36091027]
(124320,)
------
2590
[2.51323962 1.98924065 1.47266853 ... 0.75906533 0.37574795 0.07179809]
(124368,)
------
2591
[2.51323962 1.98924065 1.47266853 ... 0.36829868 0.07108501 0.02468061]
(124416,)
------
2592
[2.51323962 1.98924065 1.47266853 ... 0.06160682 0.01414986 0.2690959 ]
(124464,)
------
2593
[2.51323962 1.98924065 1.47266853 ... 0.00919688 0.25412294 0.69311738]
(124512,)
------
2594
[2.51323962 1.98924065 1.47266853 ... 0.24644119 0.68356985 1.13571155]
(124560,)
------
2595
[2.51323962 1.98924065 1.47266853 ... 0.69336468 1.14253449 1.49329793]
(124608,)
------
2596
[2.51323962 1.98924065 1.47266853 ... 1.14939594 1.50006139 1.7792505 ]
(124656,)
------
2597
[2.51323962 1.98924065 1.47266853 ... 1.49710262 1.77112389 

[2.51323962 1.98924065 1.47266853 ... 1.74716377 1.61374891 1.27109694]
(128352,)
------
2674
[2.51323962 1.98924065 1.47266853 ... 1.62475455 1.28444624 0.93056947]
(128400,)
------
2675
[2.51323962 1.98924065 1.47266853 ... 1.30106688 0.94542319 0.6015892 ]
(128448,)
------
2676
[2.51323962 1.98924065 1.47266853 ... 0.949426   0.60271186 0.2468574 ]
(128496,)
------
2677
[2.51323962 1.98924065 1.47266853 ... 0.58478302 0.23142339 0.01064485]
(128544,)
------
2678
[2.51323962 1.98924065 1.47266853 ... 0.25152576 0.04280748 0.04227517]
(128592,)
------
2679
[2.51323962 1.98924065 1.47266853 ... 0.05335267 0.06757579 0.34892055]
(128640,)
------
2680
[2.51323962 1.98924065 1.47266853 ... 0.07632983 0.36841813 0.82291621]
(128688,)
------
2681
[2.51323962 1.98924065 1.47266853 ... 0.38097668 0.83858043 1.2151686 ]
(128736,)
------
2682
[2.51323962 1.98924065 1.47266853 ... 0.85416603 1.23149788 1.57417679]
(128784,)
------
2683
[2.51323962 1.98924065 1.47266853 ... 1.24532628 1.59728968 

[2.51323962 1.98924065 1.47266853 ... 2.23003697 1.96751881 1.46709538]
(132576,)
------
2762
[2.51323962 1.98924065 1.47266853 ... 1.97714376 1.47350264 1.01230955]
(132624,)
------
2763
[2.51323962 1.98924065 1.47266853 ... 1.48125803 1.01329434 0.58391756]
(132672,)
------
2764
[2.51323962 1.98924065 1.47266853 ... 0.96540755 0.53971553 0.18462975]
(132720,)
------
2765
[2.51323962 1.98924065 1.47266853 ... 0.54902011 0.19394325 0.08129623]
(132768,)
------
2766
[2.51323962 1.98924065 1.47266853 ... 0.21118261 0.09177526 0.34394655]
(132816,)
------
2767
[2.51323962 1.98924065 1.47266853 ... 0.06959275 0.31352842 0.82135534]
(132864,)
------
2768
[2.51323962 1.98924065 1.47266853 ... 0.2856963  0.79804367 1.30073416]
(132912,)
------
2769
[2.51323962 1.98924065 1.47266853 ... 0.77896184 1.28433859 1.69566405]
(132960,)
------
2770
[2.51323962 1.98924065 1.47266853 ... 1.28683984 1.68464184 2.02388573]
(133008,)
------
2771
[2.51323962 1.98924065 1.47266853 ... 1.66998422 1.99955165 

[2.51323962 1.98924065 1.47266853 ... 2.02860045 2.39279175 2.46474791]
(136656,)
------
2847
[2.51323962 1.98924065 1.47266853 ... 2.38928461 2.46469378 2.06097102]
(136704,)
------
2848
[2.51323962 1.98924065 1.47266853 ... 2.42995    2.0235126  1.33422279]
(136752,)
------
2849
[2.51323962 1.98924065 1.47266853 ... 2.02508521 1.32906532 0.64471263]
(136800,)
------
2850
[ 2.51323962  1.98924065  1.47266853 ...  1.32634234  0.62184101
 -0.06518233]
(136848,)
------
2851
[ 2.51323962  1.98924065  1.47266853 ...  0.6071279  -0.0996696
 -0.62739825]
(136896,)
------
2852
[ 2.51323962  1.98924065  1.47266853 ... -0.12564768 -0.65673071
 -0.78252715]
(136944,)
------
2853
[ 2.51323962  1.98924065  1.47266853 ... -0.66298807 -0.79373246
 -0.43574509]
(136992,)
------
2854
[ 2.51323962  1.98924065  1.47266853 ... -0.79771405 -0.45560965
  0.29558638]
(137040,)
------
2855
[ 2.51323962  1.98924065  1.47266853 ... -0.4802964   0.25818092
  1.06149054]
(137088,)
------
2856
[2.51323962 1.98924

[2.51323962 1.98924065 1.47266853 ... 1.34955156 1.85080087 2.23283553]
(140784,)
------
2933
[2.51323962 1.98924065 1.47266853 ... 1.83290803 2.21549964 2.29298186]
(140832,)
------
2934
[2.51323962 1.98924065 1.47266853 ... 2.21848869 2.29580402 1.97464931]
(140880,)
------
2935
[2.51323962 1.98924065 1.47266853 ... 2.2916069  1.97461939 1.35686207]
(140928,)
------
2936
[2.51323962 1.98924065 1.47266853 ... 1.96476114 1.34663332 0.77050632]
(140976,)
------
2937
[2.51323962 1.98924065 1.47266853 ... 1.34530318 0.77183896 0.1865706 ]
(141024,)
------
2938
[ 2.51323962  1.98924065  1.47266853 ...  0.75984764  0.16860379
 -0.33258522]
(141072,)
------
2939
[ 2.51323962  1.98924065  1.47266853 ...  0.15953965 -0.34126046
 -0.52537835]
(141120,)
------
2940
[ 2.51323962  1.98924065  1.47266853 ... -0.34241891 -0.52515256
 -0.32189819]
(141168,)
------
2941
[ 2.51323962  1.98924065  1.47266853 ... -0.54084027 -0.33306441
  0.25355744]
(141216,)
------
2942
[ 2.51323962  1.98924065  1.4726

[2.51323962 1.98924065 1.47266853 ... 0.31974787 0.89631915 1.3752135 ]
(144912,)
------
3019
[2.51323962 1.98924065 1.47266853 ... 0.90487558 1.39610195 1.82793534]
(144960,)
------
3020
[2.51323962 1.98924065 1.47266853 ... 1.38457835 1.81713235 2.12523437]
(145008,)
------
3021
[2.51323962 1.98924065 1.47266853 ... 1.80920756 2.12477016 2.16918874]
(145056,)
------
3022
[2.51323962 1.98924065 1.47266853 ... 2.11988187 2.17491817 1.87984526]
(145104,)
------
3023
[2.51323962 1.98924065 1.47266853 ... 2.18584323 1.89567888 1.39628541]
(145152,)
------
3024
[2.51323962 1.98924065 1.47266853 ... 1.87826383 1.38887775 0.94167298]
(145200,)
------
3025
[2.51323962 1.98924065 1.47266853 ... 1.39154434 0.93656892 0.54247046]
(145248,)
------
3026
[2.51323962 1.98924065 1.47266853 ... 0.89772701 0.49982023 0.19598393]
(145296,)
------
3027
[2.51323962 1.98924065 1.47266853 ... 0.49991092 0.19592565 0.09606805]
(145344,)
------
3028
[2.51323962 1.98924065 1.47266853 ... 0.20826407 0.10585568 

[2.51323962 1.98924065 1.47266853 ... 0.61346078 1.11982739 1.53346121]
(149088,)
------
3106
[2.51323962 1.98924065 1.47266853 ... 1.09346342 1.4974823  1.86346352]
(149136,)
------
3107
[2.51323962 1.98924065 1.47266853 ... 1.50450146 1.85860479 2.10322547]
(149184,)
------
3108
[2.51323962 1.98924065 1.47266853 ... 1.85337508 2.09932685 2.11640716]
(149232,)
------
3109
[2.51323962 1.98924065 1.47266853 ... 2.098423   2.10487676 1.76740968]
(149280,)
------
3110
[2.51323962 1.98924065 1.47266853 ... 2.1175797  1.77351868 1.26790738]
(149328,)
------
3111
[2.51323962 1.98924065 1.47266853 ... 1.78683054 1.26519024 0.80230075]
(149376,)
------
3112
[2.51323962 1.98924065 1.47266853 ... 1.25317097 0.7725997  0.32077456]
(149424,)
------
3113
[ 2.51323962  1.98924065  1.47266853 ...  0.75308722  0.28964388
 -0.04429005]
(149472,)
------
3114
[ 2.51323962  1.98924065  1.47266853 ...  0.28893122 -0.0469767
 -0.09049586]
(149520,)
------
3115
[ 2.51323962  1.98924065  1.47266853 ... -0.044

[2.51323962 1.98924065 1.47266853 ... 0.8238557  1.34554482 1.77855814]
(153264,)
------
3193
[2.51323962 1.98924065 1.47266853 ... 1.35775185 1.79611933 2.14312696]
(153312,)
------
3194
[2.51323962 1.98924065 1.47266853 ... 1.78082407 2.12583661 2.17944407]
(153360,)
------
3195
[2.51323962 1.98924065 1.47266853 ... 2.12330079 2.17318797 1.83381617]
(153408,)
------
3196
[2.51323962 1.98924065 1.47266853 ... 2.18165135 1.84319222 1.28398883]
(153456,)
------
3197
[2.51323962 1.98924065 1.47266853 ... 1.8472954  1.29054677 0.81196338]
(153504,)
------
3198
[2.51323962 1.98924065 1.47266853 ... 1.29952657 0.82106036 0.35358629]
(153552,)
------
3199
[ 2.51323962  1.98924065  1.47266853 ...  0.82855541  0.36146846
 -0.04817412]
(153600,)
------
3200
[ 2.51323962  1.98924065  1.47266853 ...  0.33405247 -0.07528987
 -0.21159111]
(153648,)
------
3201
[ 2.51323962  1.98924065  1.47266853 ... -0.10780694 -0.23856418
 -0.00471127]
(153696,)
------
3202
[ 2.51323962  1.98924065  1.47266853 ..

[2.51323962 1.98924065 1.47266853 ... 1.87163353 2.24224687 2.37391067]
(157488,)
------
3281
[2.51323962 1.98924065 1.47266853 ... 2.26277781 2.38754988 2.19303942]
(157536,)
------
3282
[2.51323962 1.98924065 1.47266853 ... 2.38046503 2.16919994 1.66766703]
(157584,)
------
3283
[2.51323962 1.98924065 1.47266853 ... 2.17287374 1.68039596 1.22587895]
(157632,)
------
3284
[2.51323962 1.98924065 1.47266853 ... 1.68494415 1.23476315 0.82231426]
(157680,)
------
3285
[2.51323962 1.98924065 1.47266853 ... 1.25212634 0.84512633 0.50064033]
(157728,)
------
3286
[2.51323962 1.98924065 1.47266853 ... 0.85822266 0.51592427 0.40959811]
(157776,)
------
3287
[2.51323962 1.98924065 1.47266853 ... 0.50834727 0.40865597 0.5538491 ]
(157824,)
------
3288
[2.51323962 1.98924065 1.47266853 ... 0.4070797  0.55996561 0.95473605]
(157872,)
------
3289
[2.51323962 1.98924065 1.47266853 ... 0.57771474 0.97407341 1.45635736]
(157920,)
------
3290
[2.51323962 1.98924065 1.47266853 ... 0.98268747 1.46636164 

[2.51323962 1.98924065 1.47266853 ... 1.7482754  1.32885849 0.96012813]
(161808,)
------
3371
[2.51323962 1.98924065 1.47266853 ... 1.32483876 0.95561171 0.56740397]
(161856,)
------
3372
[2.51323962 1.98924065 1.47266853 ... 0.95118183 0.56008726 0.26215521]
(161904,)
------
3373
[2.51323962 1.98924065 1.47266853 ... 0.55109614 0.25292259 0.15840115]
(161952,)
------
3374
[2.51323962 1.98924065 1.47266853 ... 0.25488305 0.16255729 0.33399978]
(162000,)
------
3375
[2.51323962 1.98924065 1.47266853 ... 0.18618654 0.34968171 0.74483204]
(162048,)
------
3376
[2.51323962 1.98924065 1.47266853 ... 0.36246753 0.76184511 1.24256039]
(162096,)
------
3377
[2.51323962 1.98924065 1.47266853 ... 0.78563493 1.26371872 1.6500324 ]
(162144,)
------
3378
[2.51323962 1.98924065 1.47266853 ... 1.28738153 1.68110943 2.02465725]
(162192,)
------
3379
[2.51323962 1.98924065 1.47266853 ... 1.69599807 2.04093742 2.22436523]
(162240,)
------
3380
[2.51323962 1.98924065 1.47266853 ... 2.03177238 2.22032762 

[2.51323962 1.98924065 1.47266853 ... 1.92530525 1.39613485 0.94220829]
(166032,)
------
3459
[2.51323962 1.98924065 1.47266853 ... 1.38044608 0.91528106 0.46140429]
(166080,)
------
3460
[2.51323962 1.98924065 1.47266853 ... 0.89826494 0.45088014 0.15978014]
(166128,)
------
3461
[2.51323962 1.98924065 1.47266853 ... 0.48649535 0.18120921 0.19781001]
(166176,)
------
3462
[2.51323962 1.98924065 1.47266853 ... 0.20104532 0.20691419 0.61261749]
(166224,)
------
3463
[2.51323962 1.98924065 1.47266853 ... 0.20264854 0.60289246 1.18714011]
(166272,)
------
3464
[2.51323962 1.98924065 1.47266853 ... 0.60272068 1.18957639 1.68781507]
(166320,)
------
3465
[2.51323962 1.98924065 1.47266853 ... 1.19605875 1.70228803 2.16945982]
(166368,)
------
3466
[2.51323962 1.98924065 1.47266853 ... 1.71574843 2.18022943 2.50123835]
(166416,)
------
3467
[2.51323962 1.98924065 1.47266853 ... 2.16630459 2.49698043 2.57991409]
(166464,)
------
3468
[2.51323962 1.98924065 1.47266853 ... 2.49485707 2.56199527 

[2.51323962 1.98924065 1.47266853 ... 2.79311442 2.16862297 1.54744875]
(170208,)
------
3546
[2.51323962 1.98924065 1.47266853 ... 2.14743614 1.53175914 0.91419715]
(170256,)
------
3547
[2.51323962 1.98924065 1.47266853 ... 1.54101574 0.93076992 0.49760112]
(170304,)
------
3548
[2.51323962 1.98924065 1.47266853 ... 0.9282729  0.49664369 0.44041738]
(170352,)
------
3549
[2.51323962 1.98924065 1.47266853 ... 0.44284487 0.3818945  0.76077193]
(170400,)
------
3550
[2.51323962 1.98924065 1.47266853 ... 0.39171299 0.7758196  1.44729984]
(170448,)
------
3551
[2.51323962 1.98924065 1.47266853 ... 0.79234344 1.47662413 2.11463737]
(170496,)
------
3552
[2.51323962 1.98924065 1.47266853 ... 1.4817028  2.12965131 2.65576696]
(170544,)
------
3553
[2.51323962 1.98924065 1.47266853 ... 2.177351   2.71511173 3.13411522]
(170592,)
------
3554
[2.51323962 1.98924065 1.47266853 ... 2.70320058 3.12261581 3.19821835]
(170640,)
------
3555
[2.51323962 1.98924065 1.47266853 ... 3.10861325 3.1799469  

[2.51323962 1.98924065 1.47266853 ... 1.58396471 0.99523813 0.39390215]
(174432,)
------
3634
[ 2.51323962  1.98924065  1.47266853 ...  0.98601913  0.37121269
 -0.02446425]
(174480,)
------
3635
[ 2.51323962  1.98924065  1.47266853 ...  0.33454087 -0.06366173
 -0.09747037]
(174528,)
------
3636
[ 2.51323962  1.98924065  1.47266853 ... -0.1034526  -0.13134146
  0.27150726]
(174576,)
------
3637
[ 2.51323962  1.98924065  1.47266853 ... -0.15486555  0.24041182
  0.94666022]
(174624,)
------
3638
[2.51323962 1.98924065 1.47266853 ... 0.22700943 0.92713785 1.58176959]
(174672,)
------
3639
[2.51323962 1.98924065 1.47266853 ... 0.95391673 1.60692275 2.14378071]
(174720,)
------
3640
[2.51323962 1.98924065 1.47266853 ... 1.58889091 2.12487674 2.52671266]
(174768,)
------
3641
[2.51323962 1.98924065 1.47266853 ... 2.11491179 2.51809621 2.67621398]
(174816,)
------
3642
[2.51323962 1.98924065 1.47266853 ... 2.51638961 2.66970325 2.41078115]
(174864,)
------
3643
[2.51323962 1.98924065 1.4726685

[2.51323962 1.98924065 1.47266853 ... 1.8176012  1.38888741 1.02422726]
(178608,)
------
3721
[2.51323962 1.98924065 1.47266853 ... 1.38577354 1.0142616  0.70688862]
(178656,)
------
3722
[2.51323962 1.98924065 1.47266853 ... 0.98350316 0.67733401 0.52318543]
(178704,)
------
3723
[2.51323962 1.98924065 1.47266853 ... 0.69379181 0.54326844 0.68014413]
(178752,)
------
3724
[2.51323962 1.98924065 1.47266853 ... 0.54777002 0.68714696 1.0844816 ]
(178800,)
------
3725
[2.51323962 1.98924065 1.47266853 ... 0.69798499 1.091833   1.54026616]
(178848,)
------
3726
[2.51323962 1.98924065 1.47266853 ... 1.09151113 1.54521739 1.90627611]
(178896,)
------
3727
[2.51323962 1.98924065 1.47266853 ... 1.54672563 1.9088105  2.20380425]
(178944,)
------
3728
[2.51323962 1.98924065 1.47266853 ... 1.90066469 2.20022964 2.3339932 ]
(178992,)
------
3729
[2.51323962 1.98924065 1.47266853 ... 2.20116973 2.33588505 2.24526453]
(179040,)
------
3730
[2.51323962 1.98924065 1.47266853 ... 2.33519578 2.26156163 

[2.51323962 1.98924065 1.47266853 ... 1.2181021  0.85132879 0.6595217 ]
(182880,)
------
3810
[2.51323962 1.98924065 1.47266853 ... 0.83816886 0.65392321 0.75657731]
(182928,)
------
3811
[2.51323962 1.98924065 1.47266853 ... 0.63631207 0.75617886 1.17508042]
(182976,)
------
3812
[2.51323962 1.98924065 1.47266853 ... 0.75751382 1.18461442 1.68388939]
(183024,)
------
3813
[2.51323962 1.98924065 1.47266853 ... 1.18411899 1.68838549 2.0905869 ]
(183072,)
------
3814
[2.51323962 1.98924065 1.47266853 ... 1.67779219 2.07587051 2.43128037]
(183120,)
------
3815
[2.51323962 1.98924065 1.47266853 ... 2.06979299 2.42655373 2.639642  ]
(183168,)
------
3816
[2.51323962 1.98924065 1.47266853 ... 2.41669226 2.6275897  2.57015395]
(183216,)
------
3817
[2.51323962 1.98924065 1.47266853 ... 2.6341908  2.58460355 2.20551944]
(183264,)
------
3818
[2.51323962 1.98924065 1.47266853 ... 2.58130813 2.1988287  1.7289176 ]
(183312,)
------
3819
[2.51323962 1.98924065 1.47266853 ... 2.21257091 1.73796654 

[ 2.51323962  1.98924065  1.47266853 ... -0.02382624  0.01371555
  0.44717121]
(187104,)
------
3898
[2.51323962 1.98924065 1.47266853 ... 0.02532538 0.46548256 1.09224403]
(187152,)
------
3899
[2.51323962 1.98924065 1.47266853 ... 0.47718492 1.11090708 1.6401602 ]
(187200,)
------
3900
[2.51323962 1.98924065 1.47266853 ... 1.10563529 1.64127219 2.11289334]
(187248,)
------
3901
[2.51323962 1.98924065 1.47266853 ... 1.62748778 2.10036111 2.43664336]
(187296,)
------
3902
[2.51323962 1.98924065 1.47266853 ... 2.08376408 2.42279983 2.50961852]
(187344,)
------
3903
[2.51323962 1.98924065 1.47266853 ... 2.41328406 2.4946835  2.19145274]
(187392,)
------
3904
[2.51323962 1.98924065 1.47266853 ... 2.48768353 2.19207597 1.65596044]
(187440,)
------
3905
[2.51323962 1.98924065 1.47266853 ... 2.21358228 1.67388093 1.17741883]
(187488,)
------
3906
[2.51323962 1.98924065 1.47266853 ... 1.66681087 1.16712904 0.67924643]
(187536,)
------
3907
[2.51323962 1.98924065 1.47266853 ... 1.17370641 0.68

[2.51323962 1.98924065 1.47266853 ... 1.2393353  1.72175729 2.10387111]
(191376,)
------
3987
[2.51323962 1.98924065 1.47266853 ... 1.72115755 2.09662318 2.39074516]
(191424,)
------
3988
[2.51323962 1.98924065 1.47266853 ... 2.08040309 2.36108828 2.39535141]
(191472,)
------
3989
[2.51323962 1.98924065 1.47266853 ... 2.3627882  2.39685225 2.09233952]
(191520,)
------
3990
[2.51323962 1.98924065 1.47266853 ... 2.40289402 2.10093856 1.60543442]
(191568,)
------
3991
[2.51323962 1.98924065 1.47266853 ... 2.10790253 1.60745144 1.14413679]
(191616,)
------
3992
[2.51323962 1.98924065 1.47266853 ... 1.6252594  1.15331447 0.66907197]
(191664,)
------
3993
[2.51323962 1.98924065 1.47266853 ... 1.11596119 0.62403548 0.21724932]
(191712,)
------
3994
[2.51323962 1.98924065 1.47266853 ... 0.62208176 0.2133043  0.07376528]
(191760,)
------
3995
[2.51323962 1.98924065 1.47266853 ... 0.19554836 0.05883638 0.26319286]
(191808,)
------
3996
[2.51323962 1.98924065 1.47266853 ... 0.06708086 0.27452856 

[2.51323962 1.98924065 1.47266853 ... 2.23369002 2.31043839 2.10701036]
(195696,)
------
4077
[2.51323962 1.98924065 1.47266853 ... 2.30765986 2.11064887 1.69928777]
(195744,)
------
4078
[2.51323962 1.98924065 1.47266853 ... 2.12953973 1.72080076 1.32804596]
(195792,)
------
4079
[2.51323962 1.98924065 1.47266853 ... 1.71818364 1.329476   0.97882915]
(195840,)
------
4080
[2.51323962 1.98924065 1.47266853 ... 1.32139587 0.97182339 0.6993528 ]
(195888,)
------
4081
[2.51323962 1.98924065 1.47266853 ... 0.95254546 0.68258095 0.57524204]
(195936,)
------
4082
[2.51323962 1.98924065 1.47266853 ... 0.68916911 0.57747507 0.72454786]
(195984,)
------
4083
[2.51323962 1.98924065 1.47266853 ... 0.58323652 0.73337096 1.11043775]
(196032,)
------
4084
[2.51323962 1.98924065 1.47266853 ... 0.74536276 1.12781465 1.55639827]
(196080,)
------
4085
[2.51323962 1.98924065 1.47266853 ... 1.14209306 1.57561338 1.91630828]
(196128,)
------
4086
[2.51323962 1.98924065 1.47266853 ... 1.59123993 1.93559027 

[2.51323962 1.98924065 1.47266853 ... 2.03452563 2.31455755 2.33845377]
(199872,)
------
4164
[2.51323962 1.98924065 1.47266853 ... 2.30268478 2.31683707 1.94402933]
(199920,)
------
4165
[2.51323962 1.98924065 1.47266853 ... 2.3313272  1.94397128 1.38059556]
(199968,)
------
4166
[2.51323962 1.98924065 1.47266853 ... 1.96206939 1.3884263  0.86891437]
(200016,)
------
4167
[2.51323962 1.98924065 1.47266853 ... 1.36608315 0.82802773 0.28296024]
(200064,)
------
4168
[ 2.51323962  1.98924065  1.47266853 ...  0.8498745   0.28936985
 -0.09342412]
(200112,)
------
4169
[ 2.51323962  1.98924065  1.47266853 ...  0.33662924 -0.05618529
 -0.13335747]
(200160,)
------
4170
[ 2.51323962  1.98924065  1.47266853 ... -0.03127013 -0.10545707
  0.23681772]
(200208,)
------
4171
[ 2.51323962  1.98924065  1.47266853 ... -0.08946922  0.25382075
  0.89802456]
(200256,)
------
4172
[2.51323962 1.98924065 1.47266853 ... 0.23859197 0.88195467 1.47419846]
(200304,)
------
4173
[2.51323962 1.98924065 1.4726685

[2.51323962 1.98924065 1.47266853 ... 1.62004089 2.16223216 2.49451399]
(204000,)
------
4250
[2.51323962 1.98924065 1.47266853 ... 2.15630841 2.49321651 2.45395112]
(204048,)
------
4251
[2.51323962 1.98924065 1.47266853 ... 2.47468519 2.45302463 1.97726285]
(204096,)
------
4252
[2.51323962 1.98924065 1.47266853 ... 2.45701098 1.97400236 1.23560762]
(204144,)
------
4253
[2.51323962 1.98924065 1.47266853 ... 1.95768273 1.22422671 0.56771833]
(204192,)
------
4254
[ 2.51323962  1.98924065  1.47266853 ...  1.21729553  0.55727273
 -0.11640745]
(204240,)
------
4255
[ 2.51323962  1.98924065  1.47266853 ...  0.52822071 -0.15162194
 -0.6726554 ]
(204288,)
------
4256
[ 2.51323962  1.98924065  1.47266853 ... -0.15637694 -0.68317086
 -0.80244017]
(204336,)
------
4257
[ 2.51323962  1.98924065  1.47266853 ... -0.68143874 -0.80866832
 -0.4395014 ]
(204384,)
------
4258
[ 2.51323962  1.98924065  1.47266853 ... -0.81407315 -0.43827954
  0.35357308]
(204432,)
------
4259
[ 2.51323962  1.98924065 

[ 2.51323962  1.98924065  1.47266853 ... -0.13942939  0.5720582
  1.14260972]
(208080,)
------
4335
[2.51323962 1.98924065 1.47266853 ... 0.56834412 1.14145589 1.65037119]
(208128,)
------
4336
[2.51323962 1.98924065 1.47266853 ... 1.14431977 1.65940332 1.96090662]
(208176,)
------
4337
[2.51323962 1.98924065 1.47266853 ... 1.65734732 1.95684278 1.95843446]
(208224,)
------
4338
[2.51323962 1.98924065 1.47266853 ... 1.95191193 1.95504153 1.54441106]
(208272,)
------
4339
[2.51323962 1.98924065 1.47266853 ... 1.94618452 1.5330404  0.97330236]
(208320,)
------
4340
[2.51323962 1.98924065 1.47266853 ... 1.54313934 0.98602039 0.4956468 ]
(208368,)
------
4341
[2.51323962 1.98924065 1.47266853 ... 0.96876007 0.4771218  0.0323591 ]
(208416,)
------
4342
[ 2.51323962  1.98924065  1.47266853 ...  0.47831979  0.02708299
 -0.28582165]
(208464,)
------
4343
[ 2.51323962  1.98924065  1.47266853 ...  0.01090337 -0.30765399
 -0.38494715]
(208512,)
------
4344
[ 2.51323962  1.98924065  1.47266853 ...

[2.51323962 1.98924065 1.47266853 ... 0.49274564 0.94105387 1.31311309]
(212256,)
------
4422
[2.51323962 1.98924065 1.47266853 ... 0.93467075 1.31452453 1.63587701]
(212304,)
------
4423
[2.51323962 1.98924065 1.47266853 ... 1.30711484 1.62723064 1.82297957]
(212352,)
------
4424
[2.51323962 1.98924065 1.47266853 ... 1.62907445 1.82990515 1.8262974 ]
(212400,)
------
4425
[2.51323962 1.98924065 1.47266853 ... 1.82612705 1.83039999 1.56823981]
(212448,)
------
4426
[2.51323962 1.98924065 1.47266853 ... 1.8460201  1.59485579 1.20152199]
(212496,)
------
4427
[2.51323962 1.98924065 1.47266853 ... 1.59306395 1.20026171 0.8527627 ]
(212544,)
------
4428
[2.51323962 1.98924065 1.47266853 ... 1.17935228 0.83839172 0.47614002]
(212592,)
------
4429
[2.51323962 1.98924065 1.47266853 ... 0.83398265 0.46781459 0.20252864]
(212640,)
------
4430
[2.51323962 1.98924065 1.47266853 ... 0.46313143 0.20100184 0.13751204]
(212688,)
------
4431
[2.51323962 1.98924065 1.47266853 ... 0.21644509 0.14796282 

[2.51323962 1.98924065 1.47266853 ... 0.32242927 0.77907914 1.17205024]
(216432,)
------
4509
[2.51323962 1.98924065 1.47266853 ... 0.77968043 1.17696095 1.51869118]
(216480,)
------
4510
[2.51323962 1.98924065 1.47266853 ... 1.20695567 1.55611813 1.81888294]
(216528,)
------
4511
[2.51323962 1.98924065 1.47266853 ... 1.54674911 1.81329119 1.86734962]
(216576,)
------
4512
[2.51323962 1.98924065 1.47266853 ... 1.79906762 1.85831678 1.61897695]
(216624,)
------
4513
[2.51323962 1.98924065 1.47266853 ... 1.86763608 1.62571371 1.16676736]
(216672,)
------
4514
[2.51323962 1.98924065 1.47266853 ... 1.62976444 1.16956818 0.76518613]
(216720,)
------
4515
[2.51323962 1.98924065 1.47266853 ... 1.17516744 0.76686138 0.35353395]
(216768,)
------
4516
[ 2.51323962  1.98924065  1.47266853 ...  0.75403517  0.33465466
 -0.0237783 ]
(216816,)
------
4517
[ 2.51323962  1.98924065  1.47266853 ...  0.34434021 -0.01167417
 -0.1494499 ]
(216864,)
------
4518
[ 2.51323962  1.98924065  1.47266853 ...  0.02

[2.51323962 1.98924065 1.47266853 ... 0.5299511  1.14819992 1.6779927 ]
(220608,)
------
4596
[2.51323962 1.98924065 1.47266853 ... 1.12951577 1.65959072 2.09730101]
(220656,)
------
4597
[2.51323962 1.98924065 1.47266853 ... 1.67932642 2.12078691 2.33959079]
(220704,)
------
4598
[2.51323962 1.98924065 1.47266853 ... 2.12825227 2.36124182 2.2704649 ]
(220752,)
------
4599
[2.51323962 1.98924065 1.47266853 ... 2.35855246 2.26160645 1.75227702]
(220800,)
------
4600
[2.51323962 1.98924065 1.47266853 ... 2.26375675 1.74896336 1.21505868]
(220848,)
------
4601
[2.51323962 1.98924065 1.47266853 ... 1.7534771  1.22336161 0.75641394]
(220896,)
------
4602
[2.51323962 1.98924065 1.47266853 ... 1.23201013 0.76868916 0.30357078]
(220944,)
------
4603
[2.51323962 1.98924065 1.47266853 ... 0.7635141  0.30021489 0.027966  ]
(220992,)
------
4604
[2.51323962 1.98924065 1.47266853 ... 0.30026427 0.03032428 0.07669725]
(221040,)
------
4605
[2.51323962 1.98924065 1.47266853 ... 0.05450354 0.09747926 

[2.51323962 1.98924065 1.47266853 ... 0.36473671 0.89109772 1.31464469]
(224736,)
------
4682
[2.51323962 1.98924065 1.47266853 ... 0.88831377 1.31046093 1.67353535]
(224784,)
------
4683
[2.51323962 1.98924065 1.47266853 ... 1.31065929 1.67472541 1.87701166]
(224832,)
------
4684
[2.51323962 1.98924065 1.47266853 ... 1.65990818 1.86737597 1.77701092]
(224880,)
------
4685
[2.51323962 1.98924065 1.47266853 ... 1.86456013 1.77992022 1.36209619]
(224928,)
------
4686
[2.51323962 1.98924065 1.47266853 ... 1.78985023 1.37766743 0.88526583]
(224976,)
------
4687
[2.51323962 1.98924065 1.47266853 ... 1.38312721 0.89461917 0.42852354]
(225024,)
------
4688
[ 2.51323962  1.98924065  1.47266853 ...  0.86338443  0.39871192
 -0.06461384]
(225072,)
------
4689
[ 2.51323962  1.98924065  1.47266853 ...  0.40420941 -0.0589361
 -0.35801616]
(225120,)
------
4690
[ 2.51323962  1.98924065  1.47266853 ... -0.07989249 -0.38473177
 -0.38077295]
(225168,)
------
4691
[ 2.51323962  1.98924065  1.47266853 ...

[2.51323962 1.98924065 1.47266853 ... 0.55087835 1.09754741 1.58147371]
(228912,)
------
4769
[2.51323962 1.98924065 1.47266853 ... 1.10591233 1.59610212 2.01555133]
(228960,)
------
4770
[2.51323962 1.98924065 1.47266853 ... 1.61768758 2.0439961  2.30207443]
(229008,)
------
4771
[2.51323962 1.98924065 1.47266853 ... 2.04179859 2.30085397 2.29744816]
(229056,)
------
4772
[2.51323962 1.98924065 1.47266853 ... 2.30666471 2.30223775 1.95224965]
(229104,)
------
4773
[2.51323962 1.98924065 1.47266853 ... 2.28517652 1.93082333 1.44111395]
(229152,)
------
4774
[2.51323962 1.98924065 1.47266853 ... 1.92292547 1.43601131 1.00717127]
(229200,)
------
4775
[2.51323962 1.98924065 1.47266853 ... 1.42633498 1.00131845 0.59801501]
(229248,)
------
4776
[2.51323962 1.98924065 1.47266853 ... 0.99100906 0.58400613 0.28937528]
(229296,)
------
4777
[2.51323962 1.98924065 1.47266853 ... 0.58876944 0.29646033 0.22813593]
(229344,)
------
4778
[2.51323962 1.98924065 1.47266853 ... 0.30942741 0.24485014 

[2.51323962 1.98924065 1.47266853 ... 0.02139737 0.55481809 1.19909477]
(233088,)
------
4856
[2.51323962 1.98924065 1.47266853 ... 0.56039554 1.20081103 1.72036517]
(233136,)
------
4857
[2.51323962 1.98924065 1.47266853 ... 1.20770788 1.72902393 2.18779397]
(233184,)
------
4858
[2.51323962 1.98924065 1.47266853 ... 1.72159672 2.17185378 2.42706466]
(233232,)
------
4859
[2.51323962 1.98924065 1.47266853 ... 2.15423226 2.40768695 2.37138605]
(233280,)
------
4860
[2.51323962 1.98924065 1.47266853 ... 2.40467548 2.37164998 1.9466629 ]
(233328,)
------
4861
[2.51323962 1.98924065 1.47266853 ... 2.38663292 1.95570719 1.3979975 ]
(233376,)
------
4862
[2.51323962 1.98924065 1.47266853 ... 1.97126067 1.40215015 0.89981335]
(233424,)
------
4863
[2.51323962 1.98924065 1.47266853 ... 1.36507952 0.85264015 0.34913513]
(233472,)
------
4864
[2.51323962 1.98924065 1.47266853 ... 0.8952232  0.38513061 0.09909803]
(233520,)
------
4865
[2.51323962 1.98924065 1.47266853 ... 0.35292211 0.0666605  

[2.51323962 1.98924065 1.47266853 ... 0.08075726 0.6555351  1.307657  ]
(237264,)
------
4943
[2.51323962 1.98924065 1.47266853 ... 0.66277462 1.3139323  1.84651995]
(237312,)
------
4944
[2.51323962 1.98924065 1.47266853 ... 1.32192838 1.85701311 2.31641412]
(237360,)
------
4945
[2.51323962 1.98924065 1.47266853 ... 1.8611294  2.31916595 2.53791881]
(237408,)
------
4946
[2.51323962 1.98924065 1.47266853 ... 2.30618882 2.52505612 2.3954432 ]
(237456,)
------
4947
[2.51323962 1.98924065 1.47266853 ... 2.51724744 2.3938334  1.84373415]
(237504,)
------
4948
[2.51323962 1.98924065 1.47266853 ... 2.41323256 1.86459303 1.21538341]
(237552,)
------
4949
[2.51323962 1.98924065 1.47266853 ... 1.87250173 1.21635842 0.60073018]
(237600,)
------
4950
[ 2.51323962  1.98924065  1.47266853 ...  1.20207608  0.57472605
 -0.0661034 ]
(237648,)
------
4951
[ 2.51323962  1.98924065  1.47266853 ...  0.52486956 -0.1245473
 -0.52722842]
(237696,)
------
4952
[ 2.51323962  1.98924065  1.47266853 ... -0.130

[ 2.51323962  1.98924065  1.47266853 ... -0.36480674 -0.07025693
  0.55189079]
(241392,)
------
5029
[ 2.51323962  1.98924065  1.47266853 ... -0.0564993   0.56799531
  1.19824636]
(241440,)
------
5030
[2.51323962 1.98924065 1.47266853 ... 0.57380289 1.20850122 1.73570812]
(241488,)
------
5031
[2.51323962 1.98924065 1.47266853 ... 1.20946026 1.73719227 2.18038058]
(241536,)
------
5032
[2.51323962 1.98924065 1.47266853 ... 1.75659215 2.20740891 2.43770552]
(241584,)
------
5033
[2.51323962 1.98924065 1.47266853 ... 2.20754361 2.44209981 2.34165049]
(241632,)
------
5034
[2.51323962 1.98924065 1.47266853 ... 2.43119431 2.32461834 1.84582746]
(241680,)
------
5035
[2.51323962 1.98924065 1.47266853 ... 2.30524254 1.8302151  1.28900063]
(241728,)
------
5036
[2.51323962 1.98924065 1.47266853 ... 1.82474554 1.28820932 0.80768299]
(241776,)
------
5037
[2.51323962 1.98924065 1.47266853 ... 1.27782285 0.79435271 0.33974028]
(241824,)
------
5038
[2.51323962 1.98924065 1.47266853 ... 0.787740

[2.51323962 1.98924065 1.47266853 ... 0.15160644 0.11388489 0.35217309]
(245520,)
------
5115
[2.51323962 1.98924065 1.47266853 ... 0.09569114 0.34154752 0.77801758]
(245568,)
------
5116
[2.51323962 1.98924065 1.47266853 ... 0.36578664 0.80196649 1.20751953]
(245616,)
------
5117
[2.51323962 1.98924065 1.47266853 ... 0.78862268 1.19685853 1.53720915]
(245664,)
------
5118
[2.51323962 1.98924065 1.47266853 ... 1.20144379 1.54785478 1.79541647]
(245712,)
------
5119
[2.51323962 1.98924065 1.47266853 ... 1.52675045 1.78326094 1.85818958]
(245760,)
------
5120
[2.51323962 1.98924065 1.47266853 ... 1.78941119 1.86238813 1.67181766]
(245808,)
------
5121
[2.51323962 1.98924065 1.47266853 ... 1.8664335  1.68753493 1.30757952]
(245856,)
------
5122
[2.51323962 1.98924065 1.47266853 ... 1.70492852 1.32548225 0.963898  ]
(245904,)
------
5123
[2.51323962 1.98924065 1.47266853 ... 1.30699742 0.95391113 0.58890963]
(245952,)
------
5124
[2.51323962 1.98924065 1.47266853 ... 0.94820613 0.58640116 

[2.51323962 1.98924065 1.47266853 ... 0.4621377  0.65900964 1.0508641 ]
(249744,)
------
5203
[2.51323962 1.98924065 1.47266853 ... 0.65724558 1.0514425  1.42807543]
(249792,)
------
5204
[2.51323962 1.98924065 1.47266853 ... 1.04059803 1.42394984 1.74801958]
(249840,)
------
5205
[2.51323962 1.98924065 1.47266853 ... 1.45285475 1.78143489 2.03956914]
(249888,)
------
5206
[2.51323962 1.98924065 1.47266853 ... 1.78369236 2.03854299 2.10085654]
(249936,)
------
5207
[2.51323962 1.98924065 1.47266853 ... 2.03017163 2.09486985 1.92200792]
(249984,)
------
5208
[2.51323962 1.98924065 1.47266853 ... 2.09565187 1.91558778 1.5038265 ]
(250032,)
------
5209
[2.51323962 1.98924065 1.47266853 ... 1.91297662 1.50774348 1.12407148]
(250080,)
------
5210
[2.51323962 1.98924065 1.47266853 ... 1.48409808 1.10900259 0.72281665]
(250128,)
------
5211
[2.51323962 1.98924065 1.47266853 ... 1.10706174 0.721986   0.36248437]
(250176,)
------
5212
[2.51323962 1.98924065 1.47266853 ... 0.7312181  0.37542835 

[2.51323962 1.98924065 1.47266853 ... 1.56838381 2.06286597 2.4062624 ]
(254064,)
------
5293
[2.51323962 1.98924065 1.47266853 ... 2.05870104 2.40880609 2.50210977]
(254112,)
------
5294
[2.51323962 1.98924065 1.47266853 ... 2.40037918 2.49153709 2.1985538 ]
(254160,)
------
5295
[2.51323962 1.98924065 1.47266853 ... 2.49414754 2.20164704 1.63634098]
(254208,)
------
5296
[2.51323962 1.98924065 1.47266853 ... 2.21258616 1.65285814 1.21747077]
(254256,)
------
5297
[2.51323962 1.98924065 1.47266853 ... 1.6564678  1.21525061 0.75196266]
(254304,)
------
5298
[2.51323962 1.98924065 1.47266853 ... 1.22278607 0.75765365 0.32644764]
(254352,)
------
5299
[2.51323962 1.98924065 1.47266853 ... 0.74636394 0.32267413 0.1829638 ]
(254400,)
------
5300
[2.51323962 1.98924065 1.47266853 ... 0.33229291 0.18677486 0.42422089]
(254448,)
------
5301
[2.51323962 1.98924065 1.47266853 ... 0.18752337 0.41228971 0.92179209]
(254496,)
------
5302
[2.51323962 1.98924065 1.47266853 ... 0.41587284 0.93048996 

[2.51323962 1.98924065 1.47266853 ... 2.23619771 2.3852241  2.18383622]
(258288,)
------
5381
[2.51323962 1.98924065 1.47266853 ... 2.37612319 2.17822027 1.65158331]
(258336,)
------
5382
[2.51323962 1.98924065 1.47266853 ... 2.18955278 1.6639744  1.13295972]
(258384,)
------
5383
[2.51323962 1.98924065 1.47266853 ... 1.66649246 1.12980938 0.59512919]
(258432,)
------
5384
[2.51323962 1.98924065 1.47266853 ... 1.1015892  0.5561108  0.04884893]
(258480,)
------
5385
[ 2.51323962  1.98924065  1.47266853 ...  0.53202313  0.02140278
 -0.25652683]
(258528,)
------
5386
[ 2.51323962  1.98924065  1.47266853 ...  0.05057895 -0.22518142
 -0.11596209]
(258576,)
------
5387
[ 2.51323962  1.98924065  1.47266853 ... -0.20909686 -0.09420707
  0.46115115]
(258624,)
------
5388
[ 2.51323962  1.98924065  1.47266853 ... -0.0818815   0.4639647
  1.15199947]
(258672,)
------
5389
[2.51323962 1.98924065 1.47266853 ... 0.45742497 1.15010035 1.71358192]
(258720,)
------
5390
[2.51323962 1.98924065 1.47266853

[2.51323962 1.98924065 1.47266853 ... 2.5055058  2.65419579 2.47772408]
(262464,)
------
5468
[2.51323962 1.98924065 1.47266853 ... 2.66373658 2.47741008 2.00395083]
(262512,)
------
5469
[2.51323962 1.98924065 1.47266853 ... 2.4410603  1.97311699 1.50415647]
(262560,)
------
5470
[2.51323962 1.98924065 1.47266853 ... 1.93284929 1.48168278 1.0471251 ]
(262608,)
------
5471
[2.51323962 1.98924065 1.47266853 ... 1.4846946  1.04623365 0.65402335]
(262656,)
------
5472
[2.51323962 1.98924065 1.47266853 ... 1.03011405 0.6214124  0.37574801]
(262704,)
------
5473
[2.51323962 1.98924065 1.47266853 ... 0.57756633 0.32516083 0.3361744 ]
(262752,)
------
5474
[2.51323962 1.98924065 1.47266853 ... 0.30096972 0.30289254 0.62931925]
(262800,)
------
5475
[2.51323962 1.98924065 1.47266853 ... 0.22232173 0.55382538 1.07723081]
(262848,)
------
5476
[2.51323962 1.98924065 1.47266853 ... 0.59529901 1.11629295 1.57202625]
(262896,)
------
5477
[2.51323962 1.98924065 1.47266853 ... 1.12252033 1.59187186 

[2.51323962 1.98924065 1.47266853 ... 1.71376383 2.13779163 2.38614941]
(266640,)
------
5555
[2.51323962 1.98924065 1.47266853 ... 2.13250613 2.38745904 2.38988662]
(266688,)
------
5556
[2.51323962 1.98924065 1.47266853 ... 2.38592172 2.3935163  2.05254388]
(266736,)
------
5557
[2.51323962 1.98924065 1.47266853 ... 2.39140129 2.04149938 1.55677783]
(266784,)
------
5558
[2.51323962 1.98924065 1.47266853 ... 2.05350709 1.56803358 1.1531738 ]
(266832,)
------
5559
[2.51323962 1.98924065 1.47266853 ... 1.57079065 1.14909744 0.72751552]
(266880,)
------
5560
[2.51323962 1.98924065 1.47266853 ... 1.14963067 0.72514099 0.42812851]
(266928,)
------
5561
[2.51323962 1.98924065 1.47266853 ... 0.74156684 0.4466947  0.37889719]
(266976,)
------
5562
[2.51323962 1.98924065 1.47266853 ... 0.46654591 0.39033386 0.66013372]
(267024,)
------
5563
[2.51323962 1.98924065 1.47266853 ... 0.4037526  0.67894047 1.17149401]
(267072,)
------
5564
[2.51323962 1.98924065 1.47266853 ... 0.67886752 1.17559886 

[2.51323962 1.98924065 1.47266853 ... 2.2168901  2.09375501 1.62790024]
(270912,)
------
5644
[2.51323962 1.98924065 1.47266853 ... 2.10663629 1.63724339 1.12238848]
(270960,)
------
5645
[2.51323962 1.98924065 1.47266853 ... 1.6426605  1.12245166 0.61437052]
(271008,)
------
5646
[2.51323962 1.98924065 1.47266853 ... 1.08390272 0.56583571 0.04525526]
(271056,)
------
5647
[ 2.51323962  1.98924065  1.47266853 ...  0.5409646   0.01162344
 -0.31016386]
(271104,)
------
5648
[ 2.51323962  1.98924065  1.47266853 ...  0.03106296 -0.29001114
 -0.24525519]
(271152,)
------
5649
[ 2.51323962  1.98924065  1.47266853 ... -0.28811586 -0.24334335
  0.228266  ]
(271200,)
------
5650
[ 2.51323962  1.98924065  1.47266853 ... -0.23424911  0.23048295
  0.90516329]
(271248,)
------
5651
[2.51323962 1.98924065 1.47266853 ... 0.23966418 0.92060351 1.49470961]
(271296,)
------
5652
[2.51323962 1.98924065 1.47266853 ... 0.91344833 1.48449993 1.99785519]
(271344,)
------
5653
[2.51323962 1.98924065 1.4726685

[2.51323962 1.98924065 1.47266853 ... 2.11840248 1.72731447 1.35171115]
(275136,)
------
5732
[2.51323962 1.98924065 1.47266853 ... 1.71215582 1.3423301  0.98906308]
(275184,)
------
5733
[2.51323962 1.98924065 1.47266853 ... 1.33917236 0.9833892  0.6607129 ]
(275232,)
------
5734
[2.51323962 1.98924065 1.47266853 ... 0.96821451 0.64018255 0.46226564]
(275280,)
------
5735
[2.51323962 1.98924065 1.47266853 ... 0.61867714 0.43994769 0.49786153]
(275328,)
------
5736
[2.51323962 1.98924065 1.47266853 ... 0.43494284 0.49848819 0.81117064]
(275376,)
------
5737
[2.51323962 1.98924065 1.47266853 ... 0.48006901 0.79191828 1.2089777 ]
(275424,)
------
5738
[2.51323962 1.98924065 1.47266853 ... 0.78161079 1.19436693 1.52962506]
(275472,)
------
5739
[2.51323962 1.98924065 1.47266853 ... 1.17854428 1.50856113 1.79190111]
(275520,)
------
5740
[2.51323962 1.98924065 1.47266853 ... 1.50542605 1.78333127 1.92161214]
(275568,)
------
5741
[2.51323962 1.98924065 1.47266853 ... 1.78140748 1.92538726 

IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [51]:
test_ds_predict_q50_supervised = test_ds_predict_q50_all.reshape((-1, K))
test_ds_predict_q50_supervised.shape

(19168, 48)

In [52]:
test_ds_predict_q50_supervised[0:3]

array([[2.51323962, 1.98924065, 1.47266853, 0.98042303, 0.51623917,
        0.31311059, 0.4915283 , 1.02235365, 1.60488594, 2.09089375,
        2.51266265, 2.67695332, 2.51126575, 1.99715519, 1.43865931,
        0.93535393, 0.43923306, 0.13391285, 0.17786956, 0.6562708 ,
        1.31081212, 1.86701143, 2.39162993, 2.7447567 , 2.78552365,
        2.42154932, 1.80927503, 1.30479717, 0.81478333, 0.39877805,
        0.26570162, 0.55420023, 1.15904009, 1.71582699, 2.21274495,
        2.56378078, 2.63389587, 2.33708477, 1.76076174, 1.26424015,
        0.74313277, 0.25665909, 0.05603945, 0.22033411, 0.79564714,
        1.44398463, 1.98395431, 2.48369431],
       [2.0324924 , 1.50960457, 1.02110279, 0.53950405, 0.32399324,
        0.4993751 , 1.03678083, 1.63141668, 2.12082982, 2.54747581,
        2.71403599, 2.55012417, 2.040766  , 1.47410297, 0.96508646,
        0.46053386, 0.14106727, 0.17570503, 0.6460464 , 1.30219412,
        1.86458623, 2.39635301, 2.76107407, 2.8113625 , 2.45195532,
   

#### actual y

In [53]:
from helper import series_to_supervised, stage_series_to_supervised

In [54]:
test_df_supervised = series_to_supervised(test_df[['WS_S1']], n_hours, K)

In [55]:
test_df_supervised.iloc[:, -K:].shape

(19168, 48)

In [56]:
test_df_supervised_y = test_df_supervised.iloc[:, -K:]

In [57]:
test_df_supervised_y

var1(t)  var1(t+1)  var1(t+2)  var1(t+3)  var1(t+4)  var1(t+5)  \
77217     2.53       1.92       1.43       0.92       0.50       0.20   
77218     1.92       1.43       0.92       0.50       0.20       0.47   
77219     1.43       0.92       0.50       0.20       0.47       0.98   
77220     0.92       0.50       0.20       0.47       0.98       1.62   
77221     0.50       0.20       0.47       0.98       1.62       2.12   
...        ...        ...        ...        ...        ...        ...   
96380     1.95       1.96       1.62       1.14       0.73       0.15   
96381     1.96       1.62       1.14       0.73       0.15      -0.20   
96382     1.62       1.14       0.73       0.15      -0.20      -0.28   
96383     1.14       0.73       0.15      -0.20      -0.28      -0.05   
96384     0.73       0.15      -0.20      -0.28      -0.05       0.52   

       var1(t+6)  var1(t+7)  var1(t+8)  var1(t+9)  ...  var1(t+38)  \
77217       0.47       0.98       1.62       2.12  ...        1.62   
77218       0.98       1.62       2.12       2.53  ...        1.06   
77219       1.62       2.12       2.53       2.75  ...        0.46   
77220       2.12       2.53       2.75       2.59  ...       -0.07   
77221       2.53       2.75       2.59       2.05  ...       -0.16   
...          ...        ...        ...        ...  ...         ...   
96380      -0.20      -0.28      -0.05       0.52  ...        2.36   
96381      -0.28      -0.05       0.52       1.13  ...        2.18   
96382      -0.05       0.52       1.13       1.59  ...        1.69   
96383       0.52       1.13       1.59       1.99  ...        1.14   
96384       1.13       1.59       1.99       2.20  ...        0.64   

       var1(t+39)  var1(t+40)  var1(t+41)  var1(t+42)  var1(t+43)  var1(t+44)  \
77217        1.06        0.46       -0.07       -0.16        0.10        0.68   
77218        0.46       -0.07       -0.16        0.10        0.68        1.36   
77219       -0.07       -0.16        0.10        0.68        1.36        1.98   
77220       -0.16        0.10        0.68        1.36        1.98        2.48   
77221        0.10        0.68        1.36        1.98        2.48        2.80   
...           ...         ...         ...         ...         ...         ...   
96380        2.18        1.69        1.14        0.64        0.11        0.04   
96381        1.69        1.14        0.64        0.11        0.04        0.18   
96382        1.14        0.64        0.11        0.04        0.18        0.77   
96383        0.64        0.11        0.04        0.18        0.77        1.24   
96384        0.11        0.04        0.18        0.77        1.24        1.62   

       var1(t+45)  var1(t+46)  var1(t+47)  
77217        1.36        1.98        2.48  
77218        1.98        2.48        2.80  
77219        2.48        2.80        2.70  
77220        2.80        2.70        2.19  
77221        2.70        2.19        1.57  
...           ...         ...         ...  
96380        0.18        0.77        1.24  
96381        0.77        1.24        1.62  
96382        1.24        1.62        1.98  
96383        1.62        1.98        2.13  
96384        1.98        2.13        1.96  

[19168 rows x 48 columns]

#### performance on test set

In [58]:
from sklearn.metrics import mean_squared_error as mse
from sklearn.metrics import mean_absolute_error as mae


print('MAE = {}'.format(float("{:.3f}".format(mae(test_ds_predict_q50_supervised, test_df_supervised_y)))))
print('RMSE = {}'.format(float("{:.3f}".format(np.sqrt(mse(test_ds_predict_q50_supervised, test_df_supervised_y))))))

MAE = 0.157
RMSE = 0.209
